// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package email

import (
	"context"
	"database/sql"
)

const clearEmailProviderDefault = `-- name: ClearEmailProviderDefault :exec
UPDATE email_provider SET is_default = 0 WHERE is_default = 1
`

func (q *Queries) ClearEmailProviderDefault(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearEmailProviderDefault)
	return err
}

const createEmailProvider = `-- name: CreateEmailProvider :one
INSERT INTO email_provider (name, host, port, username, password, from_address, use_tls, is_default)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, host, port, username, password, from_address, use_tls, is_default, created_at
`

type CreateEmailProviderParams struct {
	Name        string `json:"name"`
	Host        string `json:"host"`
	Port        int64  `json:"port"`
	Username    string `json:"username"`
	Password    string `json:"password"`
	FromAddress string `json:"from_address"`
	UseTls      int64  `json:"use_tls"`
	IsDefault   int64  `json:"is_default"`
}

func (q *Queries) CreateEmailProvider(ctx context.Context, arg CreateEmailProviderParams) (EmailProvider, error) {
	row := q.db.QueryRowContext(ctx, createEmailProvider,
		arg.Name,
		arg.Host,
		arg.Port,
		arg.Username,
		arg.Password,
		arg.FromAddress,
		arg.UseTls,
		arg.IsDefault,
	)
	var i EmailProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.Username,
		&i.Password,
		&i.FromAddress,
		&i.UseTls,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const createEmailRecipient = `-- name: CreateEmailRecipient :one
INSERT INTO email_recipient (user_id, name, email_address)
VALUES (?, ?, ?)
RETURNING id, user_id, name, email_address, created_at
`

type CreateEmailRecipientParams struct {
	UserID       int64          `json:"user_id"`
	Name         sql.NullString `json:"name"`
	EmailAddress string         `json:"email_address"`
}

func (q *Queries) CreateEmailRecipient(ctx context.Context, arg CreateEmailRecipientParams) (EmailRecipient, error) {
	row := q.db.QueryRowContext(ctx, createEmailRecipient, arg.UserID, arg.Name, arg.EmailAddress)
	var i EmailRecipient
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.EmailAddress,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEmailProvider = `-- name: DeleteEmailProvider :exec
DELETE FROM email_provider WHERE id = ?
`

func (q *Queries) DeleteEmailProvider(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEmailProvider, id)
	return err
}

const deleteEmailRecipient = `-- name: DeleteEmailRecipient :exec
DELETE FROM email_recipient WHERE id = ?
`

func (q *Queries) DeleteEmailRecipient(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEmailRecipient, id)
	return err
}

const getBookFileForSend = `-- name: GetBookFileForSend :one
SELECT bf.file_path, bf.format, bm.title
FROM book_file bf
LEFT JOIN book_metadata bm ON bf.book_id = bm.book_id
WHERE bf.book_id = ?
ORDER BY bf.id
LIMIT 1
`

type GetBookFileForSendRow struct {
	FilePath string         `json:"file_path"`
	Format   string         `json:"format"`
	Title    sql.NullString `json:"title"`
}

func (q *Queries) GetBookFileForSend(ctx context.Context, bookID int64) (GetBookFileForSendRow, error) {
	row := q.db.QueryRowContext(ctx, getBookFileForSend, bookID)
	var i GetBookFileForSendRow
	err := row.Scan(&i.FilePath, &i.Format, &i.Title)
	return i, err
}

const getDefaultEmailProvider = `-- name: GetDefaultEmailProvider :one
SELECT id, name, host, port, username, password, from_address, use_tls, is_default, created_at FROM email_provider WHERE is_default = 1 LIMIT 1
`

func (q *Queries) GetDefaultEmailProvider(ctx context.Context) (EmailProvider, error) {
	row := q.db.QueryRowContext(ctx, getDefaultEmailProvider)
	var i EmailProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.Username,
		&i.Password,
		&i.FromAddress,
		&i.UseTls,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const getEmailProviderByID = `-- name: GetEmailProviderByID :one
SELECT id, name, host, port, username, password, from_address, use_tls, is_default, created_at FROM email_provider WHERE id = ? LIMIT 1
`

func (q *Queries) GetEmailProviderByID(ctx context.Context, id int64) (EmailProvider, error) {
	row := q.db.QueryRowContext(ctx, getEmailProviderByID, id)
	var i EmailProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.Username,
		&i.Password,
		&i.FromAddress,
		&i.UseTls,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const getEmailRecipientByID = `-- name: GetEmailRecipientByID :one
SELECT id, user_id, name, email_address, created_at FROM email_recipient WHERE id = ? LIMIT 1
`

func (q *Queries) GetEmailRecipientByID(ctx context.Context, id int64) (EmailRecipient, error) {
	row := q.db.QueryRowContext(ctx, getEmailRecipientByID, id)
	var i EmailRecipient
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.EmailAddress,
		&i.CreatedAt,
	)
	return i, err
}

const listEmailProviders = `-- name: ListEmailProviders :many
SELECT id, name, host, port, username, password, from_address, use_tls, is_default, created_at FROM email_provider ORDER BY name
`

func (q *Queries) ListEmailProviders(ctx context.Context) ([]EmailProvider, error) {
	rows, err := q.db.QueryContext(ctx, listEmailProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailProvider{}
	for rows.Next() {
		var i EmailProvider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Host,
			&i.Port,
			&i.Username,
			&i.Password,
			&i.FromAddress,
			&i.UseTls,
			&i.IsDefault,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmailRecipientsByUser = `-- name: ListEmailRecipientsByUser :many
SELECT id, user_id, name, email_address, created_at FROM email_recipient WHERE user_id = ? ORDER BY name, email_address
`

func (q *Queries) ListEmailRecipientsByUser(ctx context.Context, userID int64) ([]EmailRecipient, error) {
	rows, err := q.db.QueryContext(ctx, listEmailRecipientsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailRecipient{}
	for rows.Next() {
		var i EmailRecipient
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.EmailAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmailProvider = `-- name: UpdateEmailProvider :exec
UPDATE email_provider SET name = ?, host = ?, port = ?, username = ?, password = ?, from_address = ?, use_tls = ?, is_default = ? WHERE id = ?
`

type UpdateEmailProviderParams struct {
	Name        string `json:"name"`
	Host        string `json:"host"`
	Port        int64  `json:"port"`
	Username    string `json:"username"`
	Password    string `json:"password"`
	FromAddress string `json:"from_address"`
	UseTls      int64  `json:"use_tls"`
	IsDefault   int64  `json:"is_default"`
	ID          int64  `json:"id"`
}

func (q *Queries) UpdateEmailProvider(ctx context.Context, arg UpdateEmailProviderParams) error {
	_, err := q.db.ExecContext(ctx, updateEmailProvider,
		arg.Name,
		arg.Host,
		arg.Port,
		arg.Username,
		arg.Password,
		arg.FromAddress,
		arg.UseTls,
		arg.IsDefault,
		arg.ID,
	)
	return err
}
