// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package kobo

import (
	"context"
	"database/sql"
)

const getKoboDeviceByDeviceID = `-- name: GetKoboDeviceByDeviceID :one
SELECT id, user_id, device_id, device_name, model, firmware, last_sync_at, created_at FROM kobo_device WHERE device_id = ? LIMIT 1
`

func (q *Queries) GetKoboDeviceByDeviceID(ctx context.Context, deviceID string) (KoboDevice, error) {
	row := q.db.QueryRowContext(ctx, getKoboDeviceByDeviceID, deviceID)
	var i KoboDevice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.DeviceName,
		&i.Model,
		&i.Firmware,
		&i.LastSyncAt,
		&i.CreatedAt,
	)
	return i, err
}

const listKoboReadingStates = `-- name: ListKoboReadingStates :many
SELECT id, user_id, book_file_id, content_id, status, percent_read, current_cfi, rest_of_book_estimate, time_spent_reading, last_modified FROM kobo_reading_state WHERE user_id = ?
`

func (q *Queries) ListKoboReadingStates(ctx context.Context, userID int64) ([]KoboReadingState, error) {
	rows, err := q.db.QueryContext(ctx, listKoboReadingStates, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KoboReadingState{}
	for rows.Next() {
		var i KoboReadingState
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BookFileID,
			&i.ContentID,
			&i.Status,
			&i.PercentRead,
			&i.CurrentCfi,
			&i.RestOfBookEstimate,
			&i.TimeSpentReading,
			&i.LastModified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertKoboDevice = `-- name: UpsertKoboDevice :exec
INSERT INTO kobo_device (user_id, device_id, device_name, model, firmware, last_sync_at)
VALUES (?, ?, ?, ?, ?, datetime('now'))
ON CONFLICT(device_id) DO UPDATE SET
    device_name = excluded.device_name,
    model = excluded.model,
    firmware = excluded.firmware,
    last_sync_at = excluded.last_sync_at
`

type UpsertKoboDeviceParams struct {
	UserID     int64          `json:"user_id"`
	DeviceID   string         `json:"device_id"`
	DeviceName sql.NullString `json:"device_name"`
	Model      sql.NullString `json:"model"`
	Firmware   sql.NullString `json:"firmware"`
}

func (q *Queries) UpsertKoboDevice(ctx context.Context, arg UpsertKoboDeviceParams) error {
	_, err := q.db.ExecContext(ctx, upsertKoboDevice,
		arg.UserID,
		arg.DeviceID,
		arg.DeviceName,
		arg.Model,
		arg.Firmware,
	)
	return err
}

const upsertKoboReadingState = `-- name: UpsertKoboReadingState :exec
INSERT INTO kobo_reading_state (user_id, book_file_id, content_id, status, percent_read, current_cfi, last_modified)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(user_id, content_id) DO UPDATE SET
    status = excluded.status,
    percent_read = excluded.percent_read,
    current_cfi = excluded.current_cfi,
    last_modified = excluded.last_modified
`

type UpsertKoboReadingStateParams struct {
	UserID       int64           `json:"user_id"`
	BookFileID   int64           `json:"book_file_id"`
	ContentID    string          `json:"content_id"`
	Status       sql.NullString  `json:"status"`
	PercentRead  sql.NullFloat64 `json:"percent_read"`
	CurrentCfi   sql.NullString  `json:"current_cfi"`
	LastModified sql.NullString  `json:"last_modified"`
}

func (q *Queries) UpsertKoboReadingState(ctx context.Context, arg UpsertKoboReadingStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertKoboReadingState,
		arg.UserID,
		arg.BookFileID,
		arg.ContentID,
		arg.Status,
		arg.PercentRead,
		arg.CurrentCfi,
		arg.LastModified,
	)
	return err
}
