// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package book

import (
	"context"
	"database/sql"
)

const countBooksByLibrary = `-- name: CountBooksByLibrary :one
SELECT COUNT(*) FROM book WHERE library_id = ?
`

func (q *Queries) CountBooksByLibrary(ctx context.Context, libraryID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBooksByLibrary, libraryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBook = `-- name: CreateBook :one
INSERT INTO book (library_id, folder_path, book_type, added_date)
VALUES (?, ?, ?, datetime('now'))
RETURNING id, library_id, folder_path, book_type, created_at, added_date
`

type CreateBookParams struct {
	LibraryID  int64          `json:"library_id"`
	FolderPath sql.NullString `json:"folder_path"`
	BookType   string         `json:"book_type"`
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	row := q.db.QueryRowContext(ctx, createBook, arg.LibraryID, arg.FolderPath, arg.BookType)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.FolderPath,
		&i.BookType,
		&i.CreatedAt,
		&i.AddedDate,
	)
	return i, err
}

const createBookFile = `-- name: CreateBookFile :one
INSERT INTO book_file (book_id, file_path, format, file_size, fingerprint, track_number, track_title, duration_secs)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, book_id, file_path, format, file_size, fingerprint, track_number, track_title, duration_secs, created_at
`

type CreateBookFileParams struct {
	BookID       int64          `json:"book_id"`
	FilePath     string         `json:"file_path"`
	Format       string         `json:"format"`
	FileSize     sql.NullInt64  `json:"file_size"`
	Fingerprint  sql.NullString `json:"fingerprint"`
	TrackNumber  sql.NullInt64  `json:"track_number"`
	TrackTitle   sql.NullString `json:"track_title"`
	DurationSecs sql.NullInt64  `json:"duration_secs"`
}

func (q *Queries) CreateBookFile(ctx context.Context, arg CreateBookFileParams) (BookFile, error) {
	row := q.db.QueryRowContext(ctx, createBookFile,
		arg.BookID,
		arg.FilePath,
		arg.Format,
		arg.FileSize,
		arg.Fingerprint,
		arg.TrackNumber,
		arg.TrackTitle,
		arg.DurationSecs,
	)
	var i BookFile
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.FilePath,
		&i.Format,
		&i.FileSize,
		&i.Fingerprint,
		&i.TrackNumber,
		&i.TrackTitle,
		&i.DurationSecs,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBook = `-- name: DeleteBook :exec
DELETE FROM book WHERE id = ?
`

func (q *Queries) DeleteBook(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteBook, id)
	return err
}

const deleteBookFile = `-- name: DeleteBookFile :exec
DELETE FROM book_file WHERE id = ?
`

func (q *Queries) DeleteBookFile(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteBookFile, id)
	return err
}

const getBookByFolderPath = `-- name: GetBookByFolderPath :one
SELECT id, library_id, folder_path, book_type, created_at, added_date FROM book WHERE library_id = ? AND folder_path = ? LIMIT 1
`

type GetBookByFolderPathParams struct {
	LibraryID  int64          `json:"library_id"`
	FolderPath sql.NullString `json:"folder_path"`
}

func (q *Queries) GetBookByFolderPath(ctx context.Context, arg GetBookByFolderPathParams) (Book, error) {
	row := q.db.QueryRowContext(ctx, getBookByFolderPath, arg.LibraryID, arg.FolderPath)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.FolderPath,
		&i.BookType,
		&i.CreatedAt,
		&i.AddedDate,
	)
	return i, err
}

const getBookByID = `-- name: GetBookByID :one
SELECT id, library_id, folder_path, book_type, created_at, added_date FROM book WHERE id = ? LIMIT 1
`

func (q *Queries) GetBookByID(ctx context.Context, id int64) (Book, error) {
	row := q.db.QueryRowContext(ctx, getBookByID, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.FolderPath,
		&i.BookType,
		&i.CreatedAt,
		&i.AddedDate,
	)
	return i, err
}

const getBookFileByFingerprint = `-- name: GetBookFileByFingerprint :one
SELECT id, book_id, file_path, format, file_size, fingerprint, track_number, track_title, duration_secs, created_at FROM book_file WHERE fingerprint = ? LIMIT 1
`

func (q *Queries) GetBookFileByFingerprint(ctx context.Context, fingerprint sql.NullString) (BookFile, error) {
	row := q.db.QueryRowContext(ctx, getBookFileByFingerprint, fingerprint)
	var i BookFile
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.FilePath,
		&i.Format,
		&i.FileSize,
		&i.Fingerprint,
		&i.TrackNumber,
		&i.TrackTitle,
		&i.DurationSecs,
		&i.CreatedAt,
	)
	return i, err
}

const getBookFileByID = `-- name: GetBookFileByID :one
SELECT id, book_id, file_path, format, file_size, fingerprint, track_number, track_title, duration_secs, created_at FROM book_file WHERE id = ? LIMIT 1
`

func (q *Queries) GetBookFileByID(ctx context.Context, id int64) (BookFile, error) {
	row := q.db.QueryRowContext(ctx, getBookFileByID, id)
	var i BookFile
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.FilePath,
		&i.Format,
		&i.FileSize,
		&i.Fingerprint,
		&i.TrackNumber,
		&i.TrackTitle,
		&i.DurationSecs,
		&i.CreatedAt,
	)
	return i, err
}

const getBookFileByPath = `-- name: GetBookFileByPath :one
SELECT id, book_id, file_path, format, file_size, fingerprint, track_number, track_title, duration_secs, created_at FROM book_file WHERE file_path = ? LIMIT 1
`

func (q *Queries) GetBookFileByPath(ctx context.Context, filePath string) (BookFile, error) {
	row := q.db.QueryRowContext(ctx, getBookFileByPath, filePath)
	var i BookFile
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.FilePath,
		&i.Format,
		&i.FileSize,
		&i.Fingerprint,
		&i.TrackNumber,
		&i.TrackTitle,
		&i.DurationSecs,
		&i.CreatedAt,
	)
	return i, err
}

const getBookMetadata = `-- name: GetBookMetadata :one
SELECT book_id, title, original_title, subtitle, description, publisher, publish_date, page_count, language, isbn_10, isbn_13, google_books_id, amazon_id, goodreads_id, hardcover_id, audible_id, comicvine_id, cover_path, cover_updated_at, title_locked, subtitle_locked, description_locked, publisher_locked, publish_date_locked, page_count_locked, language_locked, isbn_10_locked, isbn_13_locked, cover_locked FROM book_metadata WHERE book_id = ? LIMIT 1
`

func (q *Queries) GetBookMetadata(ctx context.Context, bookID int64) (BookMetadatum, error) {
	row := q.db.QueryRowContext(ctx, getBookMetadata, bookID)
	var i BookMetadatum
	err := row.Scan(
		&i.BookID,
		&i.Title,
		&i.OriginalTitle,
		&i.Subtitle,
		&i.Description,
		&i.Publisher,
		&i.PublishDate,
		&i.PageCount,
		&i.Language,
		&i.Isbn10,
		&i.Isbn13,
		&i.GoogleBooksID,
		&i.AmazonID,
		&i.GoodreadsID,
		&i.HardcoverID,
		&i.AudibleID,
		&i.ComicvineID,
		&i.CoverPath,
		&i.CoverUpdatedAt,
		&i.TitleLocked,
		&i.SubtitleLocked,
		&i.DescriptionLocked,
		&i.PublisherLocked,
		&i.PublishDateLocked,
		&i.PageCountLocked,
		&i.LanguageLocked,
		&i.Isbn10Locked,
		&i.Isbn13Locked,
		&i.CoverLocked,
	)
	return i, err
}

const getBookWithLibraryID = `-- name: GetBookWithLibraryID :one
SELECT b.id, b.library_id FROM book b WHERE b.id = ? LIMIT 1
`

type GetBookWithLibraryIDRow struct {
	ID        int64 `json:"id"`
	LibraryID int64 `json:"library_id"`
}

func (q *Queries) GetBookWithLibraryID(ctx context.Context, id int64) (GetBookWithLibraryIDRow, error) {
	row := q.db.QueryRowContext(ctx, getBookWithLibraryID, id)
	var i GetBookWithLibraryIDRow
	err := row.Scan(&i.ID, &i.LibraryID)
	return i, err
}

const getBookWithMetadata = `-- name: GetBookWithMetadata :one
SELECT b.id, b.library_id, b.folder_path, b.book_type, b.created_at, b.added_date,
       bm.title, bm.subtitle, bm.description, bm.publisher, bm.publish_date,
       bm.page_count, bm.language, bm.isbn_10, bm.isbn_13, bm.cover_path,
       bm.google_books_id, bm.amazon_id, bm.goodreads_id, bm.hardcover_id
FROM book b
LEFT JOIN book_metadata bm ON b.id = bm.book_id
WHERE b.id = ? LIMIT 1
`

type GetBookWithMetadataRow struct {
	ID            int64          `json:"id"`
	LibraryID     int64          `json:"library_id"`
	FolderPath    sql.NullString `json:"folder_path"`
	BookType      string         `json:"book_type"`
	CreatedAt     string         `json:"created_at"`
	AddedDate     sql.NullString `json:"added_date"`
	Title         sql.NullString `json:"title"`
	Subtitle      sql.NullString `json:"subtitle"`
	Description   sql.NullString `json:"description"`
	Publisher     sql.NullString `json:"publisher"`
	PublishDate   sql.NullString `json:"publish_date"`
	PageCount     sql.NullInt64  `json:"page_count"`
	Language      sql.NullString `json:"language"`
	Isbn10        sql.NullString `json:"isbn_10"`
	Isbn13        sql.NullString `json:"isbn_13"`
	CoverPath     sql.NullString `json:"cover_path"`
	GoogleBooksID sql.NullString `json:"google_books_id"`
	AmazonID      sql.NullString `json:"amazon_id"`
	GoodreadsID   sql.NullString `json:"goodreads_id"`
	HardcoverID   sql.NullString `json:"hardcover_id"`
}

func (q *Queries) GetBookWithMetadata(ctx context.Context, id int64) (GetBookWithMetadataRow, error) {
	row := q.db.QueryRowContext(ctx, getBookWithMetadata, id)
	var i GetBookWithMetadataRow
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.FolderPath,
		&i.BookType,
		&i.CreatedAt,
		&i.AddedDate,
		&i.Title,
		&i.Subtitle,
		&i.Description,
		&i.Publisher,
		&i.PublishDate,
		&i.PageCount,
		&i.Language,
		&i.Isbn10,
		&i.Isbn13,
		&i.CoverPath,
		&i.GoogleBooksID,
		&i.AmazonID,
		&i.GoodreadsID,
		&i.HardcoverID,
	)
	return i, err
}

const getOrCreateAuthor = `-- name: GetOrCreateAuthor :one
INSERT INTO author (name) VALUES (?) ON CONFLICT(name) DO UPDATE SET name = name RETURNING id, name, bio, photo_path, audnexus_id
`

func (q *Queries) GetOrCreateAuthor(ctx context.Context, name string) (Author, error) {
	row := q.db.QueryRowContext(ctx, getOrCreateAuthor, name)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bio,
		&i.PhotoPath,
		&i.AudnexusID,
	)
	return i, err
}

const getOrCreateCategory = `-- name: GetOrCreateCategory :one
INSERT INTO category (name) VALUES (?) ON CONFLICT(name) DO UPDATE SET name = name RETURNING id, name
`

func (q *Queries) GetOrCreateCategory(ctx context.Context, name string) (Category, error) {
	row := q.db.QueryRowContext(ctx, getOrCreateCategory, name)
	var i Category
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getOrCreateSeries = `-- name: GetOrCreateSeries :one
INSERT INTO series (name) VALUES (?) ON CONFLICT(name) DO UPDATE SET name = name RETURNING id, name
`

func (q *Queries) GetOrCreateSeries(ctx context.Context, name string) (Series, error) {
	row := q.db.QueryRowContext(ctx, getOrCreateSeries, name)
	var i Series
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getOrCreateTag = `-- name: GetOrCreateTag :one
INSERT INTO tag (name) VALUES (?) ON CONFLICT(name) DO UPDATE SET name = name RETURNING id, name
`

func (q *Queries) GetOrCreateTag(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getOrCreateTag, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getProgress = `-- name: GetProgress :one
SELECT user_id, book_file_id, progress, progress_type, updated_at FROM user_book_file_progress WHERE user_id = ? AND book_file_id = ? LIMIT 1
`

type GetProgressParams struct {
	UserID     int64 `json:"user_id"`
	BookFileID int64 `json:"book_file_id"`
}

func (q *Queries) GetProgress(ctx context.Context, arg GetProgressParams) (UserBookFileProgress, error) {
	row := q.db.QueryRowContext(ctx, getProgress, arg.UserID, arg.BookFileID)
	var i UserBookFileProgress
	err := row.Scan(
		&i.UserID,
		&i.BookFileID,
		&i.Progress,
		&i.ProgressType,
		&i.UpdatedAt,
	)
	return i, err
}

const linkBookAuthor = `-- name: LinkBookAuthor :exec
INSERT OR IGNORE INTO book_author (book_id, author_id, sort_order) VALUES (?, ?, ?)
`

type LinkBookAuthorParams struct {
	BookID    int64 `json:"book_id"`
	AuthorID  int64 `json:"author_id"`
	SortOrder int64 `json:"sort_order"`
}

func (q *Queries) LinkBookAuthor(ctx context.Context, arg LinkBookAuthorParams) error {
	_, err := q.db.ExecContext(ctx, linkBookAuthor, arg.BookID, arg.AuthorID, arg.SortOrder)
	return err
}

const linkBookCategory = `-- name: LinkBookCategory :exec
INSERT OR IGNORE INTO book_category (book_id, category_id) VALUES (?, ?)
`

type LinkBookCategoryParams struct {
	BookID     int64 `json:"book_id"`
	CategoryID int64 `json:"category_id"`
}

func (q *Queries) LinkBookCategory(ctx context.Context, arg LinkBookCategoryParams) error {
	_, err := q.db.ExecContext(ctx, linkBookCategory, arg.BookID, arg.CategoryID)
	return err
}

const linkBookSeries = `-- name: LinkBookSeries :exec
INSERT OR IGNORE INTO book_series (book_id, series_id, series_number) VALUES (?, ?, ?)
`

type LinkBookSeriesParams struct {
	BookID       int64           `json:"book_id"`
	SeriesID     int64           `json:"series_id"`
	SeriesNumber sql.NullFloat64 `json:"series_number"`
}

func (q *Queries) LinkBookSeries(ctx context.Context, arg LinkBookSeriesParams) error {
	_, err := q.db.ExecContext(ctx, linkBookSeries, arg.BookID, arg.SeriesID, arg.SeriesNumber)
	return err
}

const linkBookTag = `-- name: LinkBookTag :exec
INSERT OR IGNORE INTO book_tag (book_id, tag_id) VALUES (?, ?)
`

type LinkBookTagParams struct {
	BookID int64 `json:"book_id"`
	TagID  int64 `json:"tag_id"`
}

func (q *Queries) LinkBookTag(ctx context.Context, arg LinkBookTagParams) error {
	_, err := q.db.ExecContext(ctx, linkBookTag, arg.BookID, arg.TagID)
	return err
}

const listBookAuthors = `-- name: ListBookAuthors :many
SELECT a.id, a.name, a.bio, a.photo_path, a.audnexus_id FROM author a JOIN book_author ba ON a.id = ba.author_id WHERE ba.book_id = ? ORDER BY ba.sort_order
`

func (q *Queries) ListBookAuthors(ctx context.Context, bookID int64) ([]Author, error) {
	rows, err := q.db.QueryContext(ctx, listBookAuthors, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Author{}
	for rows.Next() {
		var i Author
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Bio,
			&i.PhotoPath,
			&i.AudnexusID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookCategories = `-- name: ListBookCategories :many
SELECT c.id, c.name FROM category c JOIN book_category bc ON c.id = bc.category_id WHERE bc.book_id = ?
`

func (q *Queries) ListBookCategories(ctx context.Context, bookID int64) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listBookCategories, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookFiles = `-- name: ListBookFiles :many
SELECT id, book_id, file_path, format, file_size, fingerprint, track_number, track_title, duration_secs, created_at FROM book_file WHERE book_id = ? ORDER BY track_number, file_path
`

func (q *Queries) ListBookFiles(ctx context.Context, bookID int64) ([]BookFile, error) {
	rows, err := q.db.QueryContext(ctx, listBookFiles, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BookFile{}
	for rows.Next() {
		var i BookFile
		if err := rows.Scan(
			&i.ID,
			&i.BookID,
			&i.FilePath,
			&i.Format,
			&i.FileSize,
			&i.Fingerprint,
			&i.TrackNumber,
			&i.TrackTitle,
			&i.DurationSecs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookSeries = `-- name: ListBookSeries :many
SELECT s.id, s.name, bs.series_number FROM series s JOIN book_series bs ON s.id = bs.series_id WHERE bs.book_id = ?
`

type ListBookSeriesRow struct {
	ID           int64           `json:"id"`
	Name         string          `json:"name"`
	SeriesNumber sql.NullFloat64 `json:"series_number"`
}

func (q *Queries) ListBookSeries(ctx context.Context, bookID int64) ([]ListBookSeriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listBookSeries, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookSeriesRow{}
	for rows.Next() {
		var i ListBookSeriesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.SeriesNumber); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookTags = `-- name: ListBookTags :many
SELECT t.id, t.name FROM tag t JOIN book_tag bt ON t.id = bt.tag_id WHERE bt.book_id = ?
`

func (q *Queries) ListBookTags(ctx context.Context, bookID int64) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listBookTags, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBooksByLibrary = `-- name: ListBooksByLibrary :many
SELECT id, library_id, folder_path, book_type, created_at, added_date FROM book WHERE library_id = ? ORDER BY id
`

func (q *Queries) ListBooksByLibrary(ctx context.Context, libraryID int64) ([]Book, error) {
	rows, err := q.db.QueryContext(ctx, listBooksByLibrary, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Book{}
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.FolderPath,
			&i.BookType,
			&i.CreatedAt,
			&i.AddedDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBooksWithMetadata = `-- name: ListBooksWithMetadata :many
SELECT b.id, b.library_id, b.book_type, b.added_date,
       bm.title, bm.cover_path
FROM book b
LEFT JOIN book_metadata bm ON b.id = bm.book_id
WHERE b.library_id = ?
ORDER BY b.id
LIMIT ? OFFSET ?
`

type ListBooksWithMetadataParams struct {
	LibraryID int64 `json:"library_id"`
	Limit     int64 `json:"limit"`
	Offset    int64 `json:"offset"`
}

type ListBooksWithMetadataRow struct {
	ID        int64          `json:"id"`
	LibraryID int64          `json:"library_id"`
	BookType  string         `json:"book_type"`
	AddedDate sql.NullString `json:"added_date"`
	Title     sql.NullString `json:"title"`
	CoverPath sql.NullString `json:"cover_path"`
}

func (q *Queries) ListBooksWithMetadata(ctx context.Context, arg ListBooksWithMetadataParams) ([]ListBooksWithMetadataRow, error) {
	rows, err := q.db.QueryContext(ctx, listBooksWithMetadata, arg.LibraryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBooksWithMetadataRow{}
	for rows.Next() {
		var i ListBooksWithMetadataRow
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.BookType,
			&i.AddedDate,
			&i.Title,
			&i.CoverPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBookCover = `-- name: UpdateBookCover :exec
UPDATE book_metadata SET cover_path = ?, cover_updated_at = datetime('now') WHERE book_id = ?
`

type UpdateBookCoverParams struct {
	CoverPath sql.NullString `json:"cover_path"`
	BookID    int64          `json:"book_id"`
}

func (q *Queries) UpdateBookCover(ctx context.Context, arg UpdateBookCoverParams) error {
	_, err := q.db.ExecContext(ctx, updateBookCover, arg.CoverPath, arg.BookID)
	return err
}

const updateBookFileFingerprint = `-- name: UpdateBookFileFingerprint :exec
UPDATE book_file SET fingerprint = ?, file_size = ? WHERE id = ?
`

type UpdateBookFileFingerprintParams struct {
	Fingerprint sql.NullString `json:"fingerprint"`
	FileSize    sql.NullInt64  `json:"file_size"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateBookFileFingerprint(ctx context.Context, arg UpdateBookFileFingerprintParams) error {
	_, err := q.db.ExecContext(ctx, updateBookFileFingerprint, arg.Fingerprint, arg.FileSize, arg.ID)
	return err
}

const updateBookFilePath = `-- name: UpdateBookFilePath :exec
UPDATE book_file SET file_path = ? WHERE id = ?
`

type UpdateBookFilePathParams struct {
	FilePath string `json:"file_path"`
	ID       int64  `json:"id"`
}

func (q *Queries) UpdateBookFilePath(ctx context.Context, arg UpdateBookFilePathParams) error {
	_, err := q.db.ExecContext(ctx, updateBookFilePath, arg.FilePath, arg.ID)
	return err
}

const upsertBookMetadata = `-- name: UpsertBookMetadata :exec
INSERT INTO book_metadata (book_id, title, original_title, subtitle, description, publisher, publish_date, page_count, language, isbn_10, isbn_13)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(book_id) DO UPDATE SET
    title = CASE WHEN book_metadata.title_locked = 0 THEN excluded.title ELSE book_metadata.title END,
    original_title = excluded.original_title,
    subtitle = CASE WHEN book_metadata.subtitle_locked = 0 THEN excluded.subtitle ELSE book_metadata.subtitle END,
    description = CASE WHEN book_metadata.description_locked = 0 THEN excluded.description ELSE book_metadata.description END,
    publisher = CASE WHEN book_metadata.publisher_locked = 0 THEN excluded.publisher ELSE book_metadata.publisher END,
    publish_date = CASE WHEN book_metadata.publish_date_locked = 0 THEN excluded.publish_date ELSE book_metadata.publish_date END,
    page_count = CASE WHEN book_metadata.page_count_locked = 0 THEN excluded.page_count ELSE book_metadata.page_count END,
    language = CASE WHEN book_metadata.language_locked = 0 THEN excluded.language ELSE book_metadata.language END,
    isbn_10 = CASE WHEN book_metadata.isbn_10_locked = 0 THEN excluded.isbn_10 ELSE book_metadata.isbn_10 END,
    isbn_13 = CASE WHEN book_metadata.isbn_13_locked = 0 THEN excluded.isbn_13 ELSE book_metadata.isbn_13 END
`

type UpsertBookMetadataParams struct {
	BookID        int64          `json:"book_id"`
	Title         sql.NullString `json:"title"`
	OriginalTitle sql.NullString `json:"original_title"`
	Subtitle      sql.NullString `json:"subtitle"`
	Description   sql.NullString `json:"description"`
	Publisher     sql.NullString `json:"publisher"`
	PublishDate   sql.NullString `json:"publish_date"`
	PageCount     sql.NullInt64  `json:"page_count"`
	Language      sql.NullString `json:"language"`
	Isbn10        sql.NullString `json:"isbn_10"`
	Isbn13        sql.NullString `json:"isbn_13"`
}

func (q *Queries) UpsertBookMetadata(ctx context.Context, arg UpsertBookMetadataParams) error {
	_, err := q.db.ExecContext(ctx, upsertBookMetadata,
		arg.BookID,
		arg.Title,
		arg.OriginalTitle,
		arg.Subtitle,
		arg.Description,
		arg.Publisher,
		arg.PublishDate,
		arg.PageCount,
		arg.Language,
		arg.Isbn10,
		arg.Isbn13,
	)
	return err
}

const upsertProgress = `-- name: UpsertProgress :exec
INSERT INTO user_book_file_progress (user_id, book_file_id, progress, progress_type, updated_at)
VALUES (?, ?, ?, ?, datetime('now'))
ON CONFLICT(user_id, book_file_id) DO UPDATE SET
    progress = excluded.progress,
    progress_type = excluded.progress_type,
    updated_at = excluded.updated_at
`

type UpsertProgressParams struct {
	UserID       int64          `json:"user_id"`
	BookFileID   int64          `json:"book_file_id"`
	Progress     sql.NullString `json:"progress"`
	ProgressType sql.NullString `json:"progress_type"`
}

func (q *Queries) UpsertProgress(ctx context.Context, arg UpsertProgressParams) error {
	_, err := q.db.ExecContext(ctx, upsertProgress,
		arg.UserID,
		arg.BookFileID,
		arg.Progress,
		arg.ProgressType,
	)
	return err
}
