// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package reader

import (
	"context"
	"database/sql"
)

const getBookFileForReader = `-- name: GetBookFileForReader :one
SELECT bf.id, bf.book_id, bf.file_path, bf.format, b.library_id
FROM book_file bf
JOIN book b ON bf.book_id = b.id
WHERE bf.id = ? AND bf.book_id = ?
LIMIT 1
`

type GetBookFileForReaderParams struct {
	ID     int64 `json:"id"`
	BookID int64 `json:"book_id"`
}

type GetBookFileForReaderRow struct {
	ID        int64  `json:"id"`
	BookID    int64  `json:"book_id"`
	FilePath  string `json:"file_path"`
	Format    string `json:"format"`
	LibraryID int64  `json:"library_id"`
}

func (q *Queries) GetBookFileForReader(ctx context.Context, arg GetBookFileForReaderParams) (GetBookFileForReaderRow, error) {
	row := q.db.QueryRowContext(ctx, getBookFileForReader, arg.ID, arg.BookID)
	var i GetBookFileForReaderRow
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.FilePath,
		&i.Format,
		&i.LibraryID,
	)
	return i, err
}

const getReaderSettings = `-- name: GetReaderSettings :one
SELECT epub_reader_setting, pdf_reader_setting FROM user_settings WHERE user_id = ?
`

type GetReaderSettingsRow struct {
	EpubReaderSetting sql.NullString `json:"epub_reader_setting"`
	PdfReaderSetting  sql.NullString `json:"pdf_reader_setting"`
}

func (q *Queries) GetReaderSettings(ctx context.Context, userID int64) (GetReaderSettingsRow, error) {
	row := q.db.QueryRowContext(ctx, getReaderSettings, userID)
	var i GetReaderSettingsRow
	err := row.Scan(&i.EpubReaderSetting, &i.PdfReaderSetting)
	return i, err
}

const getReadingProgress = `-- name: GetReadingProgress :one
SELECT user_id, book_file_id, progress, progress_type, updated_at
FROM user_book_file_progress
WHERE user_id = ? AND book_file_id IN (
    SELECT id FROM book_file WHERE book_id = ?
)
ORDER BY updated_at DESC
LIMIT 1
`

type GetReadingProgressParams struct {
	UserID int64 `json:"user_id"`
	BookID int64 `json:"book_id"`
}

func (q *Queries) GetReadingProgress(ctx context.Context, arg GetReadingProgressParams) (UserBookFileProgress, error) {
	row := q.db.QueryRowContext(ctx, getReadingProgress, arg.UserID, arg.BookID)
	var i UserBookFileProgress
	err := row.Scan(
		&i.UserID,
		&i.BookFileID,
		&i.Progress,
		&i.ProgressType,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertEpubReaderSetting = `-- name: UpsertEpubReaderSetting :exec
INSERT INTO user_settings (user_id, epub_reader_setting)
VALUES (?, ?)
ON CONFLICT(user_id) DO UPDATE SET epub_reader_setting = excluded.epub_reader_setting
`

type UpsertEpubReaderSettingParams struct {
	UserID            int64          `json:"user_id"`
	EpubReaderSetting sql.NullString `json:"epub_reader_setting"`
}

func (q *Queries) UpsertEpubReaderSetting(ctx context.Context, arg UpsertEpubReaderSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertEpubReaderSetting, arg.UserID, arg.EpubReaderSetting)
	return err
}

const upsertPdfReaderSetting = `-- name: UpsertPdfReaderSetting :exec
INSERT INTO user_settings (user_id, pdf_reader_setting)
VALUES (?, ?)
ON CONFLICT(user_id) DO UPDATE SET pdf_reader_setting = excluded.pdf_reader_setting
`

type UpsertPdfReaderSettingParams struct {
	UserID           int64          `json:"user_id"`
	PdfReaderSetting sql.NullString `json:"pdf_reader_setting"`
}

func (q *Queries) UpsertPdfReaderSetting(ctx context.Context, arg UpsertPdfReaderSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertPdfReaderSetting, arg.UserID, arg.PdfReaderSetting)
	return err
}

const upsertReadingProgress = `-- name: UpsertReadingProgress :exec
INSERT INTO user_book_file_progress (user_id, book_file_id, progress, progress_type, updated_at)
VALUES (?, ?, ?, ?, datetime('now'))
ON CONFLICT(user_id, book_file_id) DO UPDATE SET
    progress = excluded.progress,
    progress_type = excluded.progress_type,
    updated_at = excluded.updated_at
`

type UpsertReadingProgressParams struct {
	UserID       int64          `json:"user_id"`
	BookFileID   int64          `json:"book_file_id"`
	Progress     sql.NullString `json:"progress"`
	ProgressType sql.NullString `json:"progress_type"`
}

func (q *Queries) UpsertReadingProgress(ctx context.Context, arg UpsertReadingProgressParams) error {
	_, err := q.db.ExecContext(ctx, upsertReadingProgress,
		arg.UserID,
		arg.BookFileID,
		arg.Progress,
		arg.ProgressType,
	)
	return err
}
