// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package bookdrop

import (
	"context"
	"database/sql"
)

const createBookdropFile = `-- name: CreateBookdropFile :one
INSERT INTO bookdrop_file (original_filename, file_path, file_size, status, extracted_title, extracted_authors, extracted_cover_path)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, original_filename, file_path, file_size, status, extracted_title, extracted_authors, extracted_cover_path, created_at, processed_at, imported_book_id
`

type CreateBookdropFileParams struct {
	OriginalFilename   string         `json:"original_filename"`
	FilePath           string         `json:"file_path"`
	FileSize           int64          `json:"file_size"`
	Status             string         `json:"status"`
	ExtractedTitle     sql.NullString `json:"extracted_title"`
	ExtractedAuthors   sql.NullString `json:"extracted_authors"`
	ExtractedCoverPath sql.NullString `json:"extracted_cover_path"`
}

func (q *Queries) CreateBookdropFile(ctx context.Context, arg CreateBookdropFileParams) (BookdropFile, error) {
	row := q.db.QueryRowContext(ctx, createBookdropFile,
		arg.OriginalFilename,
		arg.FilePath,
		arg.FileSize,
		arg.Status,
		arg.ExtractedTitle,
		arg.ExtractedAuthors,
		arg.ExtractedCoverPath,
	)
	var i BookdropFile
	err := row.Scan(
		&i.ID,
		&i.OriginalFilename,
		&i.FilePath,
		&i.FileSize,
		&i.Status,
		&i.ExtractedTitle,
		&i.ExtractedAuthors,
		&i.ExtractedCoverPath,
		&i.CreatedAt,
		&i.ProcessedAt,
		&i.ImportedBookID,
	)
	return i, err
}

const deleteBookdropFile = `-- name: DeleteBookdropFile :exec
DELETE FROM bookdrop_file WHERE id = ?
`

func (q *Queries) DeleteBookdropFile(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteBookdropFile, id)
	return err
}

const getBookdropFileByID = `-- name: GetBookdropFileByID :one
SELECT id, original_filename, file_path, file_size, status, extracted_title, extracted_authors, extracted_cover_path, created_at, processed_at, imported_book_id FROM bookdrop_file WHERE id = ? LIMIT 1
`

func (q *Queries) GetBookdropFileByID(ctx context.Context, id int64) (BookdropFile, error) {
	row := q.db.QueryRowContext(ctx, getBookdropFileByID, id)
	var i BookdropFile
	err := row.Scan(
		&i.ID,
		&i.OriginalFilename,
		&i.FilePath,
		&i.FileSize,
		&i.Status,
		&i.ExtractedTitle,
		&i.ExtractedAuthors,
		&i.ExtractedCoverPath,
		&i.CreatedAt,
		&i.ProcessedAt,
		&i.ImportedBookID,
	)
	return i, err
}

const listPendingBookdropFiles = `-- name: ListPendingBookdropFiles :many
SELECT id, original_filename, file_path, file_size, status, extracted_title, extracted_authors, extracted_cover_path, created_at, processed_at, imported_book_id FROM bookdrop_file WHERE status = 'PENDING' ORDER BY created_at DESC
`

func (q *Queries) ListPendingBookdropFiles(ctx context.Context) ([]BookdropFile, error) {
	rows, err := q.db.QueryContext(ctx, listPendingBookdropFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BookdropFile{}
	for rows.Next() {
		var i BookdropFile
		if err := rows.Scan(
			&i.ID,
			&i.OriginalFilename,
			&i.FilePath,
			&i.FileSize,
			&i.Status,
			&i.ExtractedTitle,
			&i.ExtractedAuthors,
			&i.ExtractedCoverPath,
			&i.CreatedAt,
			&i.ProcessedAt,
			&i.ImportedBookID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBookdropFileStatus = `-- name: UpdateBookdropFileStatus :exec
UPDATE bookdrop_file SET status = ?, processed_at = datetime('now'), imported_book_id = ? WHERE id = ?
`

type UpdateBookdropFileStatusParams struct {
	Status         string        `json:"status"`
	ImportedBookID sql.NullInt64 `json:"imported_book_id"`
	ID             int64         `json:"id"`
}

func (q *Queries) UpdateBookdropFileStatus(ctx context.Context, arg UpdateBookdropFileStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateBookdropFileStatus, arg.Status, arg.ImportedBookID, arg.ID)
	return err
}
