// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package recommendation

import (
	"database/sql"
)

type Annotation struct {
	ID         int64          `json:"id"`
	UserID     int64          `json:"user_id"`
	BookID     int64          `json:"book_id"`
	BookFileID sql.NullInt64  `json:"book_file_id"`
	Type       string         `json:"type"`
	Cfi        sql.NullString `json:"cfi"`
	PageNumber sql.NullInt64  `json:"page_number"`
	Text       sql.NullString `json:"text"`
	Note       sql.NullString `json:"note"`
	Color      string         `json:"color"`
	CreatedAt  string         `json:"created_at"`
	UpdatedAt  string         `json:"updated_at"`
}

type AppSetting struct {
	Key   string         `json:"key"`
	Value sql.NullString `json:"value"`
}

type AuditLog struct {
	ID           int64          `json:"id"`
	UserID       sql.NullInt64  `json:"user_id"`
	Username     sql.NullString `json:"username"`
	Action       string         `json:"action"`
	ResourceType sql.NullString `json:"resource_type"`
	ResourceID   sql.NullInt64  `json:"resource_id"`
	Details      sql.NullString `json:"details"`
	IpAddress    sql.NullString `json:"ip_address"`
	Country      sql.NullString `json:"country"`
	CreatedAt    string         `json:"created_at"`
}

type Author struct {
	ID         int64          `json:"id"`
	Name       string         `json:"name"`
	Bio        sql.NullString `json:"bio"`
	PhotoPath  sql.NullString `json:"photo_path"`
	AudnexusID sql.NullString `json:"audnexus_id"`
}

type Book struct {
	ID         int64          `json:"id"`
	LibraryID  int64          `json:"library_id"`
	FolderPath sql.NullString `json:"folder_path"`
	BookType   string         `json:"book_type"`
	CreatedAt  string         `json:"created_at"`
	AddedDate  sql.NullString `json:"added_date"`
}

type BookAuthor struct {
	BookID    int64 `json:"book_id"`
	AuthorID  int64 `json:"author_id"`
	SortOrder int64 `json:"sort_order"`
}

type BookCategory struct {
	BookID     int64 `json:"book_id"`
	CategoryID int64 `json:"category_id"`
}

type BookFile struct {
	ID           int64          `json:"id"`
	BookID       int64          `json:"book_id"`
	FilePath     string         `json:"file_path"`
	Format       string         `json:"format"`
	FileSize     sql.NullInt64  `json:"file_size"`
	Fingerprint  sql.NullString `json:"fingerprint"`
	TrackNumber  sql.NullInt64  `json:"track_number"`
	TrackTitle   sql.NullString `json:"track_title"`
	DurationSecs sql.NullInt64  `json:"duration_secs"`
	CreatedAt    string         `json:"created_at"`
}

type BookMetadatum struct {
	BookID            int64          `json:"book_id"`
	Title             sql.NullString `json:"title"`
	OriginalTitle     sql.NullString `json:"original_title"`
	Subtitle          sql.NullString `json:"subtitle"`
	Description       sql.NullString `json:"description"`
	Publisher         sql.NullString `json:"publisher"`
	PublishDate       sql.NullString `json:"publish_date"`
	PageCount         sql.NullInt64  `json:"page_count"`
	Language          sql.NullString `json:"language"`
	Isbn10            sql.NullString `json:"isbn_10"`
	Isbn13            sql.NullString `json:"isbn_13"`
	GoogleBooksID     sql.NullString `json:"google_books_id"`
	AmazonID          sql.NullString `json:"amazon_id"`
	GoodreadsID       sql.NullString `json:"goodreads_id"`
	HardcoverID       sql.NullString `json:"hardcover_id"`
	AudibleID         sql.NullString `json:"audible_id"`
	ComicvineID       sql.NullString `json:"comicvine_id"`
	CoverPath         sql.NullString `json:"cover_path"`
	CoverUpdatedAt    sql.NullString `json:"cover_updated_at"`
	TitleLocked       int64          `json:"title_locked"`
	SubtitleLocked    int64          `json:"subtitle_locked"`
	DescriptionLocked int64          `json:"description_locked"`
	PublisherLocked   int64          `json:"publisher_locked"`
	PublishDateLocked int64          `json:"publish_date_locked"`
	PageCountLocked   int64          `json:"page_count_locked"`
	LanguageLocked    int64          `json:"language_locked"`
	Isbn10Locked      int64          `json:"isbn_10_locked"`
	Isbn13Locked      int64          `json:"isbn_13_locked"`
	CoverLocked       int64          `json:"cover_locked"`
}

type BookMood struct {
	BookID int64 `json:"book_id"`
	MoodID int64 `json:"mood_id"`
}

type BookSeries struct {
	BookID       int64           `json:"book_id"`
	SeriesID     int64           `json:"series_id"`
	SeriesNumber sql.NullFloat64 `json:"series_number"`
}

type BookTag struct {
	BookID int64 `json:"book_id"`
	TagID  int64 `json:"tag_id"`
}

type BookVector struct {
	BookID    int64  `json:"book_id"`
	Vector    []byte `json:"vector"`
	UpdatedAt string `json:"updated_at"`
}

type Category struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type ComicMetadatum struct {
	BookID          int64           `json:"book_id"`
	Web             sql.NullString  `json:"web"`
	Volume          sql.NullInt64   `json:"volume"`
	BlackAndWhite   sql.NullInt64   `json:"black_and_white"`
	Manga           sql.NullString  `json:"manga"`
	Characters      sql.NullString  `json:"characters"`
	Teams           sql.NullString  `json:"teams"`
	Locations       sql.NullString  `json:"locations"`
	AgeRating       sql.NullString  `json:"age_rating"`
	StoryArc        sql.NullString  `json:"story_arc"`
	SeriesGroup     sql.NullString  `json:"series_group"`
	AlternateSeries sql.NullString  `json:"alternate_series"`
	AlternateNumber sql.NullFloat64 `json:"alternate_number"`
	AlternateCount  sql.NullInt64   `json:"alternate_count"`
	Count           sql.NullInt64   `json:"count"`
	Review          sql.NullString  `json:"review"`
	Type            sql.NullString  `json:"type"`
	CommunityRating sql.NullFloat64 `json:"community_rating"`
}

type KoboDevice struct {
	ID         int64          `json:"id"`
	UserID     int64          `json:"user_id"`
	DeviceID   string         `json:"device_id"`
	DeviceName sql.NullString `json:"device_name"`
	Model      sql.NullString `json:"model"`
	Firmware   sql.NullString `json:"firmware"`
	LastSyncAt sql.NullString `json:"last_sync_at"`
	CreatedAt  string         `json:"created_at"`
}

type KoboReadingState struct {
	ID                 int64           `json:"id"`
	UserID             int64           `json:"user_id"`
	BookFileID         int64           `json:"book_file_id"`
	ContentID          string          `json:"content_id"`
	Status             sql.NullString  `json:"status"`
	PercentRead        sql.NullFloat64 `json:"percent_read"`
	CurrentCfi         sql.NullString  `json:"current_cfi"`
	RestOfBookEstimate sql.NullInt64   `json:"rest_of_book_estimate"`
	TimeSpentReading   sql.NullInt64   `json:"time_spent_reading"`
	LastModified       sql.NullString  `json:"last_modified"`
}

type KoreaderProgress struct {
	ID             int64          `json:"id"`
	KoreaderUserID int64          `json:"koreader_user_id"`
	Document       string         `json:"document"`
	Progress       string         `json:"progress"`
	Percentage     float64        `json:"percentage"`
	Device         sql.NullString `json:"device"`
	DeviceID       sql.NullString `json:"device_id"`
	Timestamp      int64          `json:"timestamp"`
}

type KoreaderUser struct {
	ID          int64         `json:"id"`
	UserID      sql.NullInt64 `json:"user_id"`
	Username    string        `json:"username"`
	PasswordMd5 string        `json:"password_md5"`
	CreatedAt   string        `json:"created_at"`
}

type Library struct {
	ID                int64          `json:"id"`
	Name              string         `json:"name"`
	Icon              sql.NullString `json:"icon"`
	IconColor         sql.NullString `json:"icon_color"`
	OrganizationMode  string         `json:"organization_mode"`
	FileNamingPattern sql.NullString `json:"file_naming_pattern"`
	CreatedAt         string         `json:"created_at"`
}

type LibraryMetadataSource struct {
	LibraryID     int64  `json:"library_id"`
	Provider      string `json:"provider"`
	FieldPriority int64  `json:"field_priority"`
}

type LibraryPath struct {
	ID        int64  `json:"id"`
	LibraryID int64  `json:"library_id"`
	Path      string `json:"path"`
}

type MagicShelf struct {
	ID          int64          `json:"id"`
	UserID      int64          `json:"user_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Icon        sql.NullString `json:"icon"`
	IconColor   sql.NullString `json:"icon_color"`
	Rules       string         `json:"rules"`
	SortField   string         `json:"sort_field"`
	SortDir     string         `json:"sort_dir"`
	LimitCount  sql.NullInt64  `json:"limit_count"`
	CreatedAt   string         `json:"created_at"`
	UpdatedAt   string         `json:"updated_at"`
}

type MetadataFetchJob struct {
	ID        int64          `json:"id"`
	BookID    int64          `json:"book_id"`
	Status    string         `json:"status"`
	Provider  sql.NullString `json:"provider"`
	Error     sql.NullString `json:"error"`
	CreatedAt string         `json:"created_at"`
	UpdatedAt string         `json:"updated_at"`
}

type MetadataProposal struct {
	ID         int64          `json:"id"`
	BookID     int64          `json:"book_id"`
	Provider   string         `json:"provider"`
	ProviderID sql.NullString `json:"provider_id"`
	Status     string         `json:"status"`
	Data       string         `json:"data"`
	CreatedAt  string         `json:"created_at"`
}

type Mood struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type ReadingSession struct {
	ID            int64          `json:"id"`
	UserID        int64          `json:"user_id"`
	BookID        int64          `json:"book_id"`
	BookFileID    sql.NullInt64  `json:"book_file_id"`
	StartProgress sql.NullString `json:"start_progress"`
	EndProgress   sql.NullString `json:"end_progress"`
	StartedAt     string         `json:"started_at"`
	EndedAt       sql.NullString `json:"ended_at"`
	DurationSecs  sql.NullInt64  `json:"duration_secs"`
}

type RefreshToken struct {
	ID         int64          `json:"id"`
	UserID     int64          `json:"user_id"`
	TokenHash  string         `json:"token_hash"`
	DeviceInfo sql.NullString `json:"device_info"`
	CreatedAt  string         `json:"created_at"`
	ExpiresAt  string         `json:"expires_at"`
	Revoked    int64          `json:"revoked"`
}

type Series struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Shelf struct {
	ID          int64          `json:"id"`
	UserID      int64          `json:"user_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Icon        sql.NullString `json:"icon"`
	IconColor   sql.NullString `json:"icon_color"`
	IsPublic    int64          `json:"is_public"`
	CreatedAt   string         `json:"created_at"`
	UpdatedAt   string         `json:"updated_at"`
}

type ShelfBook struct {
	ShelfID   int64  `json:"shelf_id"`
	BookID    int64  `json:"book_id"`
	AddedAt   string `json:"added_at"`
	SortOrder int64  `json:"sort_order"`
}

type Tag struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Task struct {
	ID          int64          `json:"id"`
	TaskType    string         `json:"task_type"`
	Status      string         `json:"status"`
	Progress    sql.NullInt64  `json:"progress"`
	Total       sql.NullInt64  `json:"total"`
	Message     sql.NullString `json:"message"`
	Error       sql.NullString `json:"error"`
	Payload     sql.NullString `json:"payload"`
	CreatedAt   string         `json:"created_at"`
	UpdatedAt   string         `json:"updated_at"`
	StartedAt   sql.NullString `json:"started_at"`
	CompletedAt sql.NullString `json:"completed_at"`
}

type TaskCronConfiguration struct {
	TaskType string `json:"task_type"`
	CronExpr string `json:"cron_expr"`
	Enabled  int64  `json:"enabled"`
}

type User struct {
	ID           int64          `json:"id"`
	Username     string         `json:"username"`
	Email        sql.NullString `json:"email"`
	PasswordHash sql.NullString `json:"password_hash"`
	Name         sql.NullString `json:"name"`
	Enabled      int64          `json:"enabled"`
	CreatedAt    string         `json:"created_at"`
}

type UserBookFileProgress struct {
	UserID       int64          `json:"user_id"`
	BookFileID   int64          `json:"book_file_id"`
	Progress     sql.NullString `json:"progress"`
	ProgressType sql.NullString `json:"progress_type"`
	UpdatedAt    string         `json:"updated_at"`
}

type UserLibraryPermission struct {
	UserID    int64 `json:"user_id"`
	LibraryID int64 `json:"library_id"`
}

type UserPermission struct {
	UserID          int64  `json:"user_id"`
	Role            string `json:"role"`
	CanDownload     int64  `json:"can_download"`
	CanUpload       int64  `json:"can_upload"`
	CanEmailSend    int64  `json:"can_email_send"`
	CanEditMetadata int64  `json:"can_edit_metadata"`
	OpdsAccess      int64  `json:"opds_access"`
}

type UserSetting struct {
	UserID                 int64          `json:"user_id"`
	Theme                  sql.NullString `json:"theme"`
	BookCardsPerRow        sql.NullInt64  `json:"book_cards_per_row"`
	PdfReaderSetting       sql.NullString `json:"pdf_reader_setting"`
	EpubReaderSetting      sql.NullString `json:"epub_reader_setting"`
	ComicReaderSetting     sql.NullString `json:"comic_reader_setting"`
	AudiobookReaderSetting sql.NullString `json:"audiobook_reader_setting"`
	SidebarSetting         sql.NullString `json:"sidebar_setting"`
	DashboardSetting       sql.NullString `json:"dashboard_setting"`
}
