// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package recommendation

import (
	"context"
	"database/sql"
)

const deleteBookVector = `-- name: DeleteBookVector :exec
DELETE FROM book_vectors WHERE book_id = ?
`

func (q *Queries) DeleteBookVector(ctx context.Context, bookID int64) error {
	_, err := q.db.ExecContext(ctx, deleteBookVector, bookID)
	return err
}

const getBookVector = `-- name: GetBookVector :one
SELECT vector FROM book_vectors WHERE book_id = ? LIMIT 1
`

func (q *Queries) GetBookVector(ctx context.Context, bookID int64) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getBookVector, bookID)
	var vector []byte
	err := row.Scan(&vector)
	return vector, err
}

const listAllBookVectors = `-- name: ListAllBookVectors :many
SELECT bv.book_id, bv.vector, b.library_id, b.book_type, b.added_date, bm.title, bm.cover_path
FROM book_vectors bv
JOIN book b ON bv.book_id = b.id
LEFT JOIN book_metadata bm ON b.id = bm.book_id
`

type ListAllBookVectorsRow struct {
	BookID    int64          `json:"book_id"`
	Vector    []byte         `json:"vector"`
	LibraryID int64          `json:"library_id"`
	BookType  string         `json:"book_type"`
	AddedDate sql.NullString `json:"added_date"`
	Title     sql.NullString `json:"title"`
	CoverPath sql.NullString `json:"cover_path"`
}

func (q *Queries) ListAllBookVectors(ctx context.Context) ([]ListAllBookVectorsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllBookVectors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllBookVectorsRow{}
	for rows.Next() {
		var i ListAllBookVectorsRow
		if err := rows.Scan(
			&i.BookID,
			&i.Vector,
			&i.LibraryID,
			&i.BookType,
			&i.AddedDate,
			&i.Title,
			&i.CoverPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllBooksForVectorRebuild = `-- name: ListAllBooksForVectorRebuild :many
SELECT b.id, b.library_id, b.book_type, b.added_date,
       bm.title, bm.cover_path, bm.language, bm.publisher
FROM book b
LEFT JOIN book_metadata bm ON b.id = bm.book_id
`

type ListAllBooksForVectorRebuildRow struct {
	ID        int64          `json:"id"`
	LibraryID int64          `json:"library_id"`
	BookType  string         `json:"book_type"`
	AddedDate sql.NullString `json:"added_date"`
	Title     sql.NullString `json:"title"`
	CoverPath sql.NullString `json:"cover_path"`
	Language  sql.NullString `json:"language"`
	Publisher sql.NullString `json:"publisher"`
}

func (q *Queries) ListAllBooksForVectorRebuild(ctx context.Context) ([]ListAllBooksForVectorRebuildRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllBooksForVectorRebuild)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllBooksForVectorRebuildRow{}
	for rows.Next() {
		var i ListAllBooksForVectorRebuildRow
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.BookType,
			&i.AddedDate,
			&i.Title,
			&i.CoverPath,
			&i.Language,
			&i.Publisher,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthorsForBooks = `-- name: ListAuthorsForBooks :many
SELECT ba.book_id, a.name
FROM book_author ba
JOIN author a ON a.id = ba.author_id
WHERE ba.book_id IN (SELECT book_id FROM book_vectors)
ORDER BY ba.book_id, ba.sort_order
`

type ListAuthorsForBooksRow struct {
	BookID int64  `json:"book_id"`
	Name   string `json:"name"`
}

func (q *Queries) ListAuthorsForBooks(ctx context.Context) ([]ListAuthorsForBooksRow, error) {
	rows, err := q.db.QueryContext(ctx, listAuthorsForBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuthorsForBooksRow{}
	for rows.Next() {
		var i ListAuthorsForBooksRow
		if err := rows.Scan(&i.BookID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookAuthors = `-- name: ListBookAuthors :many
SELECT a.name FROM author a JOIN book_author ba ON a.id = ba.author_id WHERE ba.book_id = ? ORDER BY ba.sort_order
`

func (q *Queries) ListBookAuthors(ctx context.Context, bookID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listBookAuthors, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookCategories = `-- name: ListBookCategories :many
SELECT c.name FROM category c JOIN book_category bc ON c.id = bc.category_id WHERE bc.book_id = ?
`

func (q *Queries) ListBookCategories(ctx context.Context, bookID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listBookCategories, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookSeries = `-- name: ListBookSeries :many
SELECT s.name FROM series s JOIN book_series bs ON s.id = bs.series_id WHERE bs.book_id = ?
`

func (q *Queries) ListBookSeries(ctx context.Context, bookID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listBookSeries, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookTags = `-- name: ListBookTags :many
SELECT t.name FROM tag t JOIN book_tag bt ON t.id = bt.tag_id WHERE bt.book_id = ?
`

func (q *Queries) ListBookTags(ctx context.Context, bookID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listBookTags, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBookVector = `-- name: UpsertBookVector :exec
INSERT INTO book_vectors (book_id, vector, updated_at)
VALUES (?, ?, datetime('now'))
ON CONFLICT(book_id) DO UPDATE SET
    vector = excluded.vector,
    updated_at = excluded.updated_at
`

type UpsertBookVectorParams struct {
	BookID int64  `json:"book_id"`
	Vector []byte `json:"vector"`
}

func (q *Queries) UpsertBookVector(ctx context.Context, arg UpsertBookVectorParams) error {
	_, err := q.db.ExecContext(ctx, upsertBookVector, arg.BookID, arg.Vector)
	return err
}
