// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package audit

import (
	"context"
	"database/sql"
)

const countAuditLogsFiltered = `-- name: CountAuditLogsFiltered :one
SELECT COUNT(*) FROM audit_log
WHERE (? = '' OR action = ?)
  AND (CAST(COALESCE(?, -1) AS INTEGER) = -1 OR user_id = ?)
  AND (? = '' OR created_at >= ?)
  AND (? = '' OR created_at <= ?)
`

type CountAuditLogsFilteredParams struct {
	Column1     interface{}   `json:"column_1"`
	Action      string        `json:"action"`
	Column3     int64         `json:"column_3"`
	UserID      sql.NullInt64 `json:"user_id"`
	Column5     interface{}   `json:"column_5"`
	CreatedAt   string        `json:"created_at"`
	Column7     interface{}   `json:"column_7"`
	CreatedAt_2 string        `json:"created_at_2"`
}

func (q *Queries) CountAuditLogsFiltered(ctx context.Context, arg CountAuditLogsFilteredParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAuditLogsFiltered,
		arg.Column1,
		arg.Action,
		arg.Column3,
		arg.UserID,
		arg.Column5,
		arg.CreatedAt,
		arg.Column7,
		arg.CreatedAt_2,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_log (user_id, username, action, resource_type, resource_id, details, ip_address, country)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, username, "action", resource_type, resource_id, details, ip_address, country, created_at
`

type CreateAuditLogParams struct {
	UserID       sql.NullInt64  `json:"user_id"`
	Username     sql.NullString `json:"username"`
	Action       string         `json:"action"`
	ResourceType sql.NullString `json:"resource_type"`
	ResourceID   sql.NullInt64  `json:"resource_id"`
	Details      sql.NullString `json:"details"`
	IpAddress    sql.NullString `json:"ip_address"`
	Country      sql.NullString `json:"country"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRowContext(ctx, createAuditLog,
		arg.UserID,
		arg.Username,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Details,
		arg.IpAddress,
		arg.Country,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.Details,
		&i.IpAddress,
		&i.Country,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOldAuditLogs = `-- name: DeleteOldAuditLogs :exec
DELETE FROM audit_log WHERE created_at <= datetime('now', ?)
`

func (q *Queries) DeleteOldAuditLogs(ctx context.Context, datetime interface{}) error {
	_, err := q.db.ExecContext(ctx, deleteOldAuditLogs, datetime)
	return err
}

const listAuditLogsFiltered = `-- name: ListAuditLogsFiltered :many
SELECT id, user_id, username, "action", resource_type, resource_id, details, ip_address, country, created_at FROM audit_log
WHERE (? = '' OR action = ?)
  AND (CAST(COALESCE(?, -1) AS INTEGER) = -1 OR user_id = ?)
  AND (? = '' OR created_at >= ?)
  AND (? = '' OR created_at <= ?)
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListAuditLogsFilteredParams struct {
	Column1     interface{}   `json:"column_1"`
	Action      string        `json:"action"`
	Column3     int64         `json:"column_3"`
	UserID      sql.NullInt64 `json:"user_id"`
	Column5     interface{}   `json:"column_5"`
	CreatedAt   string        `json:"created_at"`
	Column7     interface{}   `json:"column_7"`
	CreatedAt_2 string        `json:"created_at_2"`
	Limit       int64         `json:"limit"`
	Offset      int64         `json:"offset"`
}

func (q *Queries) ListAuditLogsFiltered(ctx context.Context, arg ListAuditLogsFilteredParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogsFiltered,
		arg.Column1,
		arg.Action,
		arg.Column3,
		arg.UserID,
		arg.Column5,
		arg.CreatedAt,
		arg.Column7,
		arg.CreatedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Username,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Details,
			&i.IpAddress,
			&i.Country,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
