// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package contentrestriction

import (
	"context"
	"database/sql"
)

const createRestriction = `-- name: CreateRestriction :one
INSERT INTO user_content_restriction (user_id, restriction_type, value, mode)
VALUES (?, ?, ?, ?)
RETURNING id, user_id, restriction_type, value, mode
`

type CreateRestrictionParams struct {
	UserID          int64  `json:"user_id"`
	RestrictionType string `json:"restriction_type"`
	Value           string `json:"value"`
	Mode            string `json:"mode"`
}

func (q *Queries) CreateRestriction(ctx context.Context, arg CreateRestrictionParams) (UserContentRestriction, error) {
	row := q.db.QueryRowContext(ctx, createRestriction,
		arg.UserID,
		arg.RestrictionType,
		arg.Value,
		arg.Mode,
	)
	var i UserContentRestriction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RestrictionType,
		&i.Value,
		&i.Mode,
	)
	return i, err
}

const deleteRestriction = `-- name: DeleteRestriction :exec
DELETE FROM user_content_restriction WHERE id = ? AND user_id = ?
`

type DeleteRestrictionParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteRestriction(ctx context.Context, arg DeleteRestrictionParams) error {
	_, err := q.db.ExecContext(ctx, deleteRestriction, arg.ID, arg.UserID)
	return err
}

const getBookIDsByAgeRating = `-- name: GetBookIDsByAgeRating :many
SELECT book_id FROM comic_metadata WHERE age_rating = ?
`

func (q *Queries) GetBookIDsByAgeRating(ctx context.Context, ageRating sql.NullString) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getBookIDsByAgeRating, ageRating)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var book_id int64
		if err := rows.Scan(&book_id); err != nil {
			return nil, err
		}
		items = append(items, book_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookIDsByCategoryValue = `-- name: GetBookIDsByCategoryValue :many
SELECT bc.book_id FROM book_category bc
JOIN category c ON c.id = bc.category_id
WHERE c.name = ?
`

func (q *Queries) GetBookIDsByCategoryValue(ctx context.Context, name string) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getBookIDsByCategoryValue, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var book_id int64
		if err := rows.Scan(&book_id); err != nil {
			return nil, err
		}
		items = append(items, book_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookIDsByMoodValue = `-- name: GetBookIDsByMoodValue :many
SELECT bm.book_id FROM book_mood bm
JOIN mood m ON m.id = bm.mood_id
WHERE m.name = ?
`

func (q *Queries) GetBookIDsByMoodValue(ctx context.Context, name string) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getBookIDsByMoodValue, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var book_id int64
		if err := rows.Scan(&book_id); err != nil {
			return nil, err
		}
		items = append(items, book_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookIDsByTagValue = `-- name: GetBookIDsByTagValue :many
SELECT bt.book_id FROM book_tag bt
JOIN tag t ON t.id = bt.tag_id
WHERE t.name = ?
`

func (q *Queries) GetBookIDsByTagValue(ctx context.Context, name string) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getBookIDsByTagValue, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var book_id int64
		if err := rows.Scan(&book_id); err != nil {
			return nil, err
		}
		items = append(items, book_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRestrictionsByUser = `-- name: ListRestrictionsByUser :many
SELECT id, user_id, restriction_type, value, mode FROM user_content_restriction WHERE user_id = ? ORDER BY restriction_type, value
`

func (q *Queries) ListRestrictionsByUser(ctx context.Context, userID int64) ([]UserContentRestriction, error) {
	rows, err := q.db.QueryContext(ctx, listRestrictionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserContentRestriction{}
	for rows.Next() {
		var i UserContentRestriction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RestrictionType,
			&i.Value,
			&i.Mode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRestrictionMode = `-- name: UpdateRestrictionMode :exec
UPDATE user_content_restriction SET mode = ? WHERE id = ? AND user_id = ?
`

type UpdateRestrictionModeParams struct {
	Mode   string `json:"mode"`
	ID     int64  `json:"id"`
	UserID int64  `json:"user_id"`
}

func (q *Queries) UpdateRestrictionMode(ctx context.Context, arg UpdateRestrictionModeParams) error {
	_, err := q.db.ExecContext(ctx, updateRestrictionMode, arg.Mode, arg.ID, arg.UserID)
	return err
}
