// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package koreader

import (
	"context"
	"database/sql"
)

const createKOReaderUser = `-- name: CreateKOReaderUser :one
INSERT INTO koreader_user (user_id, username, password_md5)
VALUES (?, ?, ?)
RETURNING id, user_id, username, password_md5, created_at
`

type CreateKOReaderUserParams struct {
	UserID      sql.NullInt64 `json:"user_id"`
	Username    string        `json:"username"`
	PasswordMd5 string        `json:"password_md5"`
}

func (q *Queries) CreateKOReaderUser(ctx context.Context, arg CreateKOReaderUserParams) (KoreaderUser, error) {
	row := q.db.QueryRowContext(ctx, createKOReaderUser, arg.UserID, arg.Username, arg.PasswordMd5)
	var i KoreaderUser
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.PasswordMd5,
		&i.CreatedAt,
	)
	return i, err
}

const getKOReaderProgress = `-- name: GetKOReaderProgress :one
SELECT id, koreader_user_id, document, progress, percentage, device, device_id, timestamp FROM koreader_progress WHERE koreader_user_id = ? AND document = ? LIMIT 1
`

type GetKOReaderProgressParams struct {
	KoreaderUserID int64  `json:"koreader_user_id"`
	Document       string `json:"document"`
}

func (q *Queries) GetKOReaderProgress(ctx context.Context, arg GetKOReaderProgressParams) (KoreaderProgress, error) {
	row := q.db.QueryRowContext(ctx, getKOReaderProgress, arg.KoreaderUserID, arg.Document)
	var i KoreaderProgress
	err := row.Scan(
		&i.ID,
		&i.KoreaderUserID,
		&i.Document,
		&i.Progress,
		&i.Percentage,
		&i.Device,
		&i.DeviceID,
		&i.Timestamp,
	)
	return i, err
}

const getKOReaderUserByUsername = `-- name: GetKOReaderUserByUsername :one
SELECT id, user_id, username, password_md5, created_at FROM koreader_user WHERE username = ? LIMIT 1
`

func (q *Queries) GetKOReaderUserByUsername(ctx context.Context, username string) (KoreaderUser, error) {
	row := q.db.QueryRowContext(ctx, getKOReaderUserByUsername, username)
	var i KoreaderUser
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.PasswordMd5,
		&i.CreatedAt,
	)
	return i, err
}

const upsertKOReaderProgress = `-- name: UpsertKOReaderProgress :one
INSERT INTO koreader_progress (koreader_user_id, document, progress, percentage, device, device_id, timestamp)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(koreader_user_id, document) DO UPDATE SET
    progress = excluded.progress,
    percentage = excluded.percentage,
    device = excluded.device,
    device_id = excluded.device_id,
    timestamp = excluded.timestamp
RETURNING id, koreader_user_id, document, progress, percentage, device, device_id, timestamp
`

type UpsertKOReaderProgressParams struct {
	KoreaderUserID int64          `json:"koreader_user_id"`
	Document       string         `json:"document"`
	Progress       string         `json:"progress"`
	Percentage     float64        `json:"percentage"`
	Device         sql.NullString `json:"device"`
	DeviceID       sql.NullString `json:"device_id"`
	Timestamp      int64          `json:"timestamp"`
}

func (q *Queries) UpsertKOReaderProgress(ctx context.Context, arg UpsertKOReaderProgressParams) (KoreaderProgress, error) {
	row := q.db.QueryRowContext(ctx, upsertKOReaderProgress,
		arg.KoreaderUserID,
		arg.Document,
		arg.Progress,
		arg.Percentage,
		arg.Device,
		arg.DeviceID,
		arg.Timestamp,
	)
	var i KoreaderProgress
	err := row.Scan(
		&i.ID,
		&i.KoreaderUserID,
		&i.Document,
		&i.Progress,
		&i.Percentage,
		&i.Device,
		&i.DeviceID,
		&i.Timestamp,
	)
	return i, err
}
