// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package task

import (
	"context"
	"database/sql"
)

const cancelTask = `-- name: CancelTask :exec
UPDATE tasks SET status = 'CANCELLED', updated_at = datetime('now') WHERE id = ? AND status IN ('QUEUED', 'RUNNING')
`

func (q *Queries) CancelTask(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, cancelTask, id)
	return err
}

const completeTask = `-- name: CompleteTask :exec
UPDATE tasks SET status = 'COMPLETED', completed_at = datetime('now'), updated_at = datetime('now') WHERE id = ?
`

func (q *Queries) CompleteTask(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, completeTask, id)
	return err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (task_type, status, payload)
VALUES (?, 'QUEUED', ?)
RETURNING id, task_type, status, progress, total, message, error, payload, created_at, updated_at, started_at, completed_at
`

type CreateTaskParams struct {
	TaskType string         `json:"task_type"`
	Payload  sql.NullString `json:"payload"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask, arg.TaskType, arg.Payload)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TaskType,
		&i.Status,
		&i.Progress,
		&i.Total,
		&i.Message,
		&i.Error,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const failTask = `-- name: FailTask :exec
UPDATE tasks SET status = 'FAILED', error = ?, completed_at = datetime('now'), updated_at = datetime('now') WHERE id = ?
`

type FailTaskParams struct {
	Error sql.NullString `json:"error"`
	ID    int64          `json:"id"`
}

func (q *Queries) FailTask(ctx context.Context, arg FailTaskParams) error {
	_, err := q.db.ExecContext(ctx, failTask, arg.Error, arg.ID)
	return err
}

const getCronConfig = `-- name: GetCronConfig :one
SELECT task_type, cron_expr, enabled FROM task_cron_configuration WHERE task_type = ? LIMIT 1
`

func (q *Queries) GetCronConfig(ctx context.Context, taskType string) (TaskCronConfiguration, error) {
	row := q.db.QueryRowContext(ctx, getCronConfig, taskType)
	var i TaskCronConfiguration
	err := row.Scan(&i.TaskType, &i.CronExpr, &i.Enabled)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT id, task_type, status, progress, total, message, error, payload, created_at, updated_at, started_at, completed_at FROM tasks WHERE id = ? LIMIT 1
`

func (q *Queries) GetTask(ctx context.Context, id int64) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TaskType,
		&i.Status,
		&i.Progress,
		&i.Total,
		&i.Message,
		&i.Error,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listCronConfigs = `-- name: ListCronConfigs :many
SELECT task_type, cron_expr, enabled FROM task_cron_configuration ORDER BY task_type
`

func (q *Queries) ListCronConfigs(ctx context.Context) ([]TaskCronConfiguration, error) {
	rows, err := q.db.QueryContext(ctx, listCronConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskCronConfiguration{}
	for rows.Next() {
		var i TaskCronConfiguration
		if err := rows.Scan(&i.TaskType, &i.CronExpr, &i.Enabled); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentTasks = `-- name: ListRecentTasks :many
SELECT id, task_type, status, progress, total, message, error, payload, created_at, updated_at, started_at, completed_at FROM tasks ORDER BY created_at DESC LIMIT 50
`

func (q *Queries) ListRecentTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listRecentTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.TaskType,
			&i.Status,
			&i.Progress,
			&i.Total,
			&i.Message,
			&i.Error,
			&i.Payload,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInterruptedTasksFailed = `-- name: MarkInterruptedTasksFailed :exec
UPDATE tasks SET status = 'FAILED', error = 'interrupted by server restart', updated_at = datetime('now')
WHERE status = 'RUNNING'
`

func (q *Queries) MarkInterruptedTasksFailed(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, markInterruptedTasksFailed)
	return err
}

const startTask = `-- name: StartTask :exec
UPDATE tasks SET status = 'RUNNING', started_at = datetime('now'), updated_at = datetime('now') WHERE id = ?
`

func (q *Queries) StartTask(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, startTask, id)
	return err
}

const updateTaskProgress = `-- name: UpdateTaskProgress :exec
UPDATE tasks SET progress = ?, total = ?, message = ?, updated_at = datetime('now') WHERE id = ?
`

type UpdateTaskProgressParams struct {
	Progress sql.NullInt64  `json:"progress"`
	Total    sql.NullInt64  `json:"total"`
	Message  sql.NullString `json:"message"`
	ID       int64          `json:"id"`
}

func (q *Queries) UpdateTaskProgress(ctx context.Context, arg UpdateTaskProgressParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskProgress,
		arg.Progress,
		arg.Total,
		arg.Message,
		arg.ID,
	)
	return err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :exec
UPDATE tasks SET status = ?, updated_at = datetime('now') WHERE id = ?
`

type UpdateTaskStatusParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskStatus, arg.Status, arg.ID)
	return err
}

const upsertCronConfig = `-- name: UpsertCronConfig :exec
INSERT INTO task_cron_configuration (task_type, cron_expr, enabled)
VALUES (?, ?, ?)
ON CONFLICT(task_type) DO UPDATE SET cron_expr = excluded.cron_expr, enabled = excluded.enabled
`

type UpsertCronConfigParams struct {
	TaskType string `json:"task_type"`
	CronExpr string `json:"cron_expr"`
	Enabled  int64  `json:"enabled"`
}

func (q *Queries) UpsertCronConfig(ctx context.Context, arg UpsertCronConfigParams) error {
	_, err := q.db.ExecContext(ctx, upsertCronConfig, arg.TaskType, arg.CronExpr, arg.Enabled)
	return err
}
