// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package user

import (
	"database/sql"
)

type AppSetting struct {
	Key   string         `json:"key"`
	Value sql.NullString `json:"value"`
}

type RefreshToken struct {
	ID         int64          `json:"id"`
	UserID     int64          `json:"user_id"`
	TokenHash  string         `json:"token_hash"`
	DeviceInfo sql.NullString `json:"device_info"`
	CreatedAt  string         `json:"created_at"`
	ExpiresAt  string         `json:"expires_at"`
	Revoked    int64          `json:"revoked"`
}

type User struct {
	ID           int64          `json:"id"`
	Username     string         `json:"username"`
	Email        sql.NullString `json:"email"`
	PasswordHash sql.NullString `json:"password_hash"`
	Name         sql.NullString `json:"name"`
	Enabled      int64          `json:"enabled"`
	CreatedAt    string         `json:"created_at"`
}

type UserPermission struct {
	UserID          int64  `json:"user_id"`
	Role            string `json:"role"`
	CanDownload     int64  `json:"can_download"`
	CanUpload       int64  `json:"can_upload"`
	CanEmailSend    int64  `json:"can_email_send"`
	CanEditMetadata int64  `json:"can_edit_metadata"`
	OpdsAccess      int64  `json:"opds_access"`
}

type UserSetting struct {
	UserID                 int64          `json:"user_id"`
	Theme                  sql.NullString `json:"theme"`
	BookCardsPerRow        sql.NullInt64  `json:"book_cards_per_row"`
	PdfReaderSetting       sql.NullString `json:"pdf_reader_setting"`
	EpubReaderSetting      sql.NullString `json:"epub_reader_setting"`
	ComicReaderSetting     sql.NullString `json:"comic_reader_setting"`
	AudiobookReaderSetting sql.NullString `json:"audiobook_reader_setting"`
	SidebarSetting         sql.NullString `json:"sidebar_setting"`
	DashboardSetting       sql.NullString `json:"dashboard_setting"`
}
