// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package user

import (
	"context"
	"database/sql"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (user_id, token_hash, device_info, expires_at)
VALUES (?, ?, ?, ?)
`

type CreateRefreshTokenParams struct {
	UserID     int64          `json:"user_id"`
	TokenHash  string         `json:"token_hash"`
	DeviceInfo sql.NullString `json:"device_info"`
	ExpiresAt  string         `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, createRefreshToken,
		arg.UserID,
		arg.TokenHash,
		arg.DeviceInfo,
		arg.ExpiresAt,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, password_hash, name)
VALUES (?, ?, ?, ?)
RETURNING id, username, email, password_hash, name, enabled, created_at
`

type CreateUserParams struct {
	Username     string         `json:"username"`
	Email        sql.NullString `json:"email"`
	PasswordHash sql.NullString `json:"password_hash"`
	Name         sql.NullString `json:"name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :exec
DELETE FROM refresh_tokens WHERE expires_at < datetime('now') OR revoked = 1
`

func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredRefreshTokens)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getAppSetting = `-- name: GetAppSetting :one
SELECT value FROM app_settings WHERE key = ?
`

func (q *Queries) GetAppSetting(ctx context.Context, key string) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getAppSetting, key)
	var value sql.NullString
	err := row.Scan(&value)
	return value, err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, user_id, token_hash, device_info, created_at, expires_at, revoked FROM refresh_tokens WHERE token_hash = ? AND revoked = 0
`

func (q *Queries) GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getRefreshToken, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.DeviceInfo,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Revoked,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, name, enabled, created_at FROM users WHERE email = ? LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password_hash, name, enabled, created_at FROM users WHERE id = ? LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password_hash, name, enabled, created_at FROM users WHERE username = ? LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const getUserPermissions = `-- name: GetUserPermissions :one
SELECT user_id, role, can_download, can_upload, can_email_send, can_edit_metadata, opds_access FROM user_permissions WHERE user_id = ?
`

func (q *Queries) GetUserPermissions(ctx context.Context, userID int64) (UserPermission, error) {
	row := q.db.QueryRowContext(ctx, getUserPermissions, userID)
	var i UserPermission
	err := row.Scan(
		&i.UserID,
		&i.Role,
		&i.CanDownload,
		&i.CanUpload,
		&i.CanEmailSend,
		&i.CanEditMetadata,
		&i.OpdsAccess,
	)
	return i, err
}

const getUserSettings = `-- name: GetUserSettings :one
SELECT user_id, theme, book_cards_per_row, pdf_reader_setting, epub_reader_setting, comic_reader_setting, audiobook_reader_setting, sidebar_setting, dashboard_setting FROM user_settings WHERE user_id = ?
`

func (q *Queries) GetUserSettings(ctx context.Context, userID int64) (UserSetting, error) {
	row := q.db.QueryRowContext(ctx, getUserSettings, userID)
	var i UserSetting
	err := row.Scan(
		&i.UserID,
		&i.Theme,
		&i.BookCardsPerRow,
		&i.PdfReaderSetting,
		&i.EpubReaderSetting,
		&i.ComicReaderSetting,
		&i.AudiobookReaderSetting,
		&i.SidebarSetting,
		&i.DashboardSetting,
	)
	return i, err
}

const getUserSettingsFull = `-- name: GetUserSettingsFull :one
SELECT user_id, theme, book_cards_per_row, pdf_reader_setting, epub_reader_setting, comic_reader_setting, audiobook_reader_setting, sidebar_setting, dashboard_setting FROM user_settings WHERE user_id = ?
`

func (q *Queries) GetUserSettingsFull(ctx context.Context, userID int64) (UserSetting, error) {
	row := q.db.QueryRowContext(ctx, getUserSettingsFull, userID)
	var i UserSetting
	err := row.Scan(
		&i.UserID,
		&i.Theme,
		&i.BookCardsPerRow,
		&i.PdfReaderSetting,
		&i.EpubReaderSetting,
		&i.ComicReaderSetting,
		&i.AudiobookReaderSetting,
		&i.SidebarSetting,
		&i.DashboardSetting,
	)
	return i, err
}

const listUserLibraryIDs = `-- name: ListUserLibraryIDs :many
SELECT library_id FROM user_library_permission WHERE user_id = ?
`

func (q *Queries) ListUserLibraryIDs(ctx context.Context, userID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listUserLibraryIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var library_id int64
		if err := rows.Scan(&library_id); err != nil {
			return nil, err
		}
		items = append(items, library_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, password_hash, name, enabled, created_at FROM users ORDER BY username
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.Name,
			&i.Enabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllUserRefreshTokens = `-- name: RevokeAllUserRefreshTokens :exec
UPDATE refresh_tokens SET revoked = 1 WHERE user_id = ?
`

func (q *Queries) RevokeAllUserRefreshTokens(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, revokeAllUserRefreshTokens, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens SET revoked = 1 WHERE token_hash = ?
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, revokeRefreshToken, tokenHash)
	return err
}

const updateDashboardSetting = `-- name: UpdateDashboardSetting :exec
UPDATE user_settings SET dashboard_setting = ? WHERE user_id = ?
`

type UpdateDashboardSettingParams struct {
	DashboardSetting sql.NullString `json:"dashboard_setting"`
	UserID           int64          `json:"user_id"`
}

func (q *Queries) UpdateDashboardSetting(ctx context.Context, arg UpdateDashboardSettingParams) error {
	_, err := q.db.ExecContext(ctx, updateDashboardSetting, arg.DashboardSetting, arg.UserID)
	return err
}

const updateEpubReaderSetting = `-- name: UpdateEpubReaderSetting :exec
UPDATE user_settings SET epub_reader_setting = ? WHERE user_id = ?
`

type UpdateEpubReaderSettingParams struct {
	EpubReaderSetting sql.NullString `json:"epub_reader_setting"`
	UserID            int64          `json:"user_id"`
}

func (q *Queries) UpdateEpubReaderSetting(ctx context.Context, arg UpdateEpubReaderSettingParams) error {
	_, err := q.db.ExecContext(ctx, updateEpubReaderSetting, arg.EpubReaderSetting, arg.UserID)
	return err
}

const updatePdfReaderSetting = `-- name: UpdatePdfReaderSetting :exec
UPDATE user_settings SET pdf_reader_setting = ? WHERE user_id = ?
`

type UpdatePdfReaderSettingParams struct {
	PdfReaderSetting sql.NullString `json:"pdf_reader_setting"`
	UserID           int64          `json:"user_id"`
}

func (q *Queries) UpdatePdfReaderSetting(ctx context.Context, arg UpdatePdfReaderSettingParams) error {
	_, err := q.db.ExecContext(ctx, updatePdfReaderSetting, arg.PdfReaderSetting, arg.UserID)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users SET email = ?, name = ?, enabled = ? WHERE id = ?
`

type UpdateUserParams struct {
	Email   sql.NullString `json:"email"`
	Name    sql.NullString `json:"name"`
	Enabled int64          `json:"enabled"`
	ID      int64          `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.Email,
		arg.Name,
		arg.Enabled,
		arg.ID,
	)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = ? WHERE id = ?
`

type UpdateUserPasswordParams struct {
	PasswordHash sql.NullString `json:"password_hash"`
	ID           int64          `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	return err
}

const upsertAppSetting = `-- name: UpsertAppSetting :exec
INSERT INTO app_settings (key, value) VALUES (?, ?)
ON CONFLICT(key) DO UPDATE SET value = excluded.value
`

type UpsertAppSettingParams struct {
	Key   string         `json:"key"`
	Value sql.NullString `json:"value"`
}

func (q *Queries) UpsertAppSetting(ctx context.Context, arg UpsertAppSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertAppSetting, arg.Key, arg.Value)
	return err
}

const upsertUserPermissions = `-- name: UpsertUserPermissions :exec
INSERT INTO user_permissions (user_id, role, can_download, can_upload, can_email_send, can_edit_metadata, opds_access)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(user_id) DO UPDATE SET
    role = excluded.role,
    can_download = excluded.can_download,
    can_upload = excluded.can_upload,
    can_email_send = excluded.can_email_send,
    can_edit_metadata = excluded.can_edit_metadata,
    opds_access = excluded.opds_access
`

type UpsertUserPermissionsParams struct {
	UserID          int64  `json:"user_id"`
	Role            string `json:"role"`
	CanDownload     int64  `json:"can_download"`
	CanUpload       int64  `json:"can_upload"`
	CanEmailSend    int64  `json:"can_email_send"`
	CanEditMetadata int64  `json:"can_edit_metadata"`
	OpdsAccess      int64  `json:"opds_access"`
}

func (q *Queries) UpsertUserPermissions(ctx context.Context, arg UpsertUserPermissionsParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserPermissions,
		arg.UserID,
		arg.Role,
		arg.CanDownload,
		arg.CanUpload,
		arg.CanEmailSend,
		arg.CanEditMetadata,
		arg.OpdsAccess,
	)
	return err
}

const upsertUserSettings = `-- name: UpsertUserSettings :exec
INSERT INTO user_settings (user_id, theme, book_cards_per_row)
VALUES (?, ?, ?)
ON CONFLICT(user_id) DO UPDATE SET
    theme = excluded.theme,
    book_cards_per_row = excluded.book_cards_per_row
`

type UpsertUserSettingsParams struct {
	UserID          int64          `json:"user_id"`
	Theme           sql.NullString `json:"theme"`
	BookCardsPerRow sql.NullInt64  `json:"book_cards_per_row"`
}

func (q *Queries) UpsertUserSettings(ctx context.Context, arg UpsertUserSettingsParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserSettings, arg.UserID, arg.Theme, arg.BookCardsPerRow)
	return err
}
