// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package metadata

import (
	"context"
	"database/sql"
)

const createMetadataProposal = `-- name: CreateMetadataProposal :one
INSERT INTO metadata_proposal (book_id, provider, provider_id, status, data)
VALUES (?, ?, ?, 'PENDING', ?)
RETURNING id, book_id, provider, provider_id, status, data, created_at
`

type CreateMetadataProposalParams struct {
	BookID     int64          `json:"book_id"`
	Provider   string         `json:"provider"`
	ProviderID sql.NullString `json:"provider_id"`
	Data       string         `json:"data"`
}

func (q *Queries) CreateMetadataProposal(ctx context.Context, arg CreateMetadataProposalParams) (MetadataProposal, error) {
	row := q.db.QueryRowContext(ctx, createMetadataProposal,
		arg.BookID,
		arg.Provider,
		arg.ProviderID,
		arg.Data,
	)
	var i MetadataProposal
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.Provider,
		&i.ProviderID,
		&i.Status,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const getMetadataProposal = `-- name: GetMetadataProposal :one
SELECT id, book_id, provider, provider_id, status, data, created_at FROM metadata_proposal WHERE id = ? LIMIT 1
`

func (q *Queries) GetMetadataProposal(ctx context.Context, id int64) (MetadataProposal, error) {
	row := q.db.QueryRowContext(ctx, getMetadataProposal, id)
	var i MetadataProposal
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.Provider,
		&i.ProviderID,
		&i.Status,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const listMetadataProposals = `-- name: ListMetadataProposals :many
SELECT id, book_id, provider, provider_id, status, data, created_at FROM metadata_proposal WHERE book_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListMetadataProposals(ctx context.Context, bookID int64) ([]MetadataProposal, error) {
	rows, err := q.db.QueryContext(ctx, listMetadataProposals, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MetadataProposal{}
	for rows.Next() {
		var i MetadataProposal
		if err := rows.Scan(
			&i.ID,
			&i.BookID,
			&i.Provider,
			&i.ProviderID,
			&i.Status,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingProposals = `-- name: ListPendingProposals :many
SELECT mp.id, mp.book_id, mp.provider, mp.provider_id, mp.status, mp.data, mp.created_at, bm.title as book_title
FROM metadata_proposal mp
LEFT JOIN book_metadata bm ON mp.book_id = bm.book_id
WHERE mp.status = 'PENDING'
ORDER BY mp.created_at DESC
`

type ListPendingProposalsRow struct {
	ID         int64          `json:"id"`
	BookID     int64          `json:"book_id"`
	Provider   string         `json:"provider"`
	ProviderID sql.NullString `json:"provider_id"`
	Status     string         `json:"status"`
	Data       string         `json:"data"`
	CreatedAt  string         `json:"created_at"`
	BookTitle  sql.NullString `json:"book_title"`
}

func (q *Queries) ListPendingProposals(ctx context.Context) ([]ListPendingProposalsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingProposals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingProposalsRow{}
	for rows.Next() {
		var i ListPendingProposalsRow
		if err := rows.Scan(
			&i.ID,
			&i.BookID,
			&i.Provider,
			&i.ProviderID,
			&i.Status,
			&i.Data,
			&i.CreatedAt,
			&i.BookTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProposalStatus = `-- name: UpdateProposalStatus :exec
UPDATE metadata_proposal SET status = ? WHERE id = ?
`

type UpdateProposalStatusParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateProposalStatus(ctx context.Context, arg UpdateProposalStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateProposalStatus, arg.Status, arg.ID)
	return err
}
