// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: magic_queries.sql

package shelf

import (
	"context"
	"database/sql"
)

const createMagicShelf = `-- name: CreateMagicShelf :one
INSERT INTO magic_shelf (user_id, name, description, icon, icon_color, rules, sort_field, sort_dir, limit_count)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, name, description, icon, icon_color, rules, sort_field, sort_dir, limit_count, created_at, updated_at
`

type CreateMagicShelfParams struct {
	UserID      int64          `json:"user_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Icon        sql.NullString `json:"icon"`
	IconColor   sql.NullString `json:"icon_color"`
	Rules       string         `json:"rules"`
	SortField   string         `json:"sort_field"`
	SortDir     string         `json:"sort_dir"`
	LimitCount  sql.NullInt64  `json:"limit_count"`
}

func (q *Queries) CreateMagicShelf(ctx context.Context, arg CreateMagicShelfParams) (MagicShelf, error) {
	row := q.db.QueryRowContext(ctx, createMagicShelf,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.Icon,
		arg.IconColor,
		arg.Rules,
		arg.SortField,
		arg.SortDir,
		arg.LimitCount,
	)
	var i MagicShelf
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.IconColor,
		&i.Rules,
		&i.SortField,
		&i.SortDir,
		&i.LimitCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMagicShelf = `-- name: DeleteMagicShelf :exec
DELETE FROM magic_shelf WHERE id = ? AND user_id = ?
`

type DeleteMagicShelfParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteMagicShelf(ctx context.Context, arg DeleteMagicShelfParams) error {
	_, err := q.db.ExecContext(ctx, deleteMagicShelf, arg.ID, arg.UserID)
	return err
}

const getMagicShelfByID = `-- name: GetMagicShelfByID :one
SELECT id, user_id, name, description, icon, icon_color, rules, sort_field, sort_dir, limit_count, created_at, updated_at FROM magic_shelf WHERE id = ? LIMIT 1
`

func (q *Queries) GetMagicShelfByID(ctx context.Context, id int64) (MagicShelf, error) {
	row := q.db.QueryRowContext(ctx, getMagicShelfByID, id)
	var i MagicShelf
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.IconColor,
		&i.Rules,
		&i.SortField,
		&i.SortDir,
		&i.LimitCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMagicShelvesForUser = `-- name: ListMagicShelvesForUser :many
SELECT id, user_id, name, description, icon, icon_color, rules, sort_field, sort_dir, limit_count, created_at, updated_at FROM magic_shelf WHERE user_id = ? ORDER BY name
`

func (q *Queries) ListMagicShelvesForUser(ctx context.Context, userID int64) ([]MagicShelf, error) {
	rows, err := q.db.QueryContext(ctx, listMagicShelvesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MagicShelf{}
	for rows.Next() {
		var i MagicShelf
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.IconColor,
			&i.Rules,
			&i.SortField,
			&i.SortDir,
			&i.LimitCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMagicShelf = `-- name: UpdateMagicShelf :exec
UPDATE magic_shelf SET name = ?, description = ?, icon = ?, icon_color = ?, rules = ?,
    sort_field = ?, sort_dir = ?, limit_count = ?, updated_at = datetime('now')
WHERE id = ? AND user_id = ?
`

type UpdateMagicShelfParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Icon        sql.NullString `json:"icon"`
	IconColor   sql.NullString `json:"icon_color"`
	Rules       string         `json:"rules"`
	SortField   string         `json:"sort_field"`
	SortDir     string         `json:"sort_dir"`
	LimitCount  sql.NullInt64  `json:"limit_count"`
	ID          int64          `json:"id"`
	UserID      int64          `json:"user_id"`
}

func (q *Queries) UpdateMagicShelf(ctx context.Context, arg UpdateMagicShelfParams) error {
	_, err := q.db.ExecContext(ctx, updateMagicShelf,
		arg.Name,
		arg.Description,
		arg.Icon,
		arg.IconColor,
		arg.Rules,
		arg.SortField,
		arg.SortDir,
		arg.LimitCount,
		arg.ID,
		arg.UserID,
	)
	return err
}
