// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package shelf

import (
	"context"
	"database/sql"
)

const addBookToShelf = `-- name: AddBookToShelf :exec
INSERT OR IGNORE INTO shelf_book (shelf_id, book_id, sort_order)
VALUES (?, ?, (SELECT COALESCE(MAX(sb2.sort_order), 0) + 1 FROM shelf_book sb2 WHERE sb2.shelf_id = ?))
`

type AddBookToShelfParams struct {
	ShelfID   int64 `json:"shelf_id"`
	BookID    int64 `json:"book_id"`
	ShelfID_2 int64 `json:"shelf_id_2"`
}

func (q *Queries) AddBookToShelf(ctx context.Context, arg AddBookToShelfParams) error {
	_, err := q.db.ExecContext(ctx, addBookToShelf, arg.ShelfID, arg.BookID, arg.ShelfID_2)
	return err
}

const countBooksInShelf = `-- name: CountBooksInShelf :one
SELECT COUNT(*) FROM shelf_book WHERE shelf_id = ?
`

func (q *Queries) CountBooksInShelf(ctx context.Context, shelfID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBooksInShelf, shelfID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createShelf = `-- name: CreateShelf :one
INSERT INTO shelf (user_id, name, description, icon, icon_color, is_public)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, user_id, name, description, icon, icon_color, is_public, created_at, updated_at
`

type CreateShelfParams struct {
	UserID      int64          `json:"user_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Icon        sql.NullString `json:"icon"`
	IconColor   sql.NullString `json:"icon_color"`
	IsPublic    int64          `json:"is_public"`
}

func (q *Queries) CreateShelf(ctx context.Context, arg CreateShelfParams) (Shelf, error) {
	row := q.db.QueryRowContext(ctx, createShelf,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.Icon,
		arg.IconColor,
		arg.IsPublic,
	)
	var i Shelf
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.IconColor,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteShelf = `-- name: DeleteShelf :exec
DELETE FROM shelf WHERE id = ? AND user_id = ?
`

type DeleteShelfParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteShelf(ctx context.Context, arg DeleteShelfParams) error {
	_, err := q.db.ExecContext(ctx, deleteShelf, arg.ID, arg.UserID)
	return err
}

const getShelfByID = `-- name: GetShelfByID :one
SELECT id, user_id, name, description, icon, icon_color, is_public, created_at, updated_at FROM shelf WHERE id = ? LIMIT 1
`

func (q *Queries) GetShelfByID(ctx context.Context, id int64) (Shelf, error) {
	row := q.db.QueryRowContext(ctx, getShelfByID, id)
	var i Shelf
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.IconColor,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isBookInShelf = `-- name: IsBookInShelf :one
SELECT COUNT(*) FROM shelf_book WHERE shelf_id = ? AND book_id = ?
`

type IsBookInShelfParams struct {
	ShelfID int64 `json:"shelf_id"`
	BookID  int64 `json:"book_id"`
}

func (q *Queries) IsBookInShelf(ctx context.Context, arg IsBookInShelfParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, isBookInShelf, arg.ShelfID, arg.BookID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listBooksInShelf = `-- name: ListBooksInShelf :many
SELECT b.id, b.library_id, b.book_type, b.added_date,
       bm.title, bm.cover_path,
       sb.sort_order, sb.added_at
FROM shelf_book sb
JOIN book b ON b.id = sb.book_id
LEFT JOIN book_metadata bm ON bm.book_id = b.id
WHERE sb.shelf_id = ?
ORDER BY sb.sort_order, sb.added_at
`

type ListBooksInShelfRow struct {
	ID        int64          `json:"id"`
	LibraryID int64          `json:"library_id"`
	BookType  string         `json:"book_type"`
	AddedDate sql.NullString `json:"added_date"`
	Title     sql.NullString `json:"title"`
	CoverPath sql.NullString `json:"cover_path"`
	SortOrder int64          `json:"sort_order"`
	AddedAt   string         `json:"added_at"`
}

func (q *Queries) ListBooksInShelf(ctx context.Context, shelfID int64) ([]ListBooksInShelfRow, error) {
	rows, err := q.db.QueryContext(ctx, listBooksInShelf, shelfID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBooksInShelfRow{}
	for rows.Next() {
		var i ListBooksInShelfRow
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.BookType,
			&i.AddedDate,
			&i.Title,
			&i.CoverPath,
			&i.SortOrder,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShelvesContainingBook = `-- name: ListShelvesContainingBook :many
SELECT s.id, s.user_id, s.name, s.description, s.icon, s.icon_color, s.is_public, s.created_at, s.updated_at FROM shelf s
JOIN shelf_book sb ON sb.shelf_id = s.id
WHERE sb.book_id = ? AND s.user_id = ?
`

type ListShelvesContainingBookParams struct {
	BookID int64 `json:"book_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) ListShelvesContainingBook(ctx context.Context, arg ListShelvesContainingBookParams) ([]Shelf, error) {
	rows, err := q.db.QueryContext(ctx, listShelvesContainingBook, arg.BookID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Shelf{}
	for rows.Next() {
		var i Shelf
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.IconColor,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShelvesForUser = `-- name: ListShelvesForUser :many
SELECT id, user_id, name, description, icon, icon_color, is_public, created_at, updated_at FROM shelf WHERE user_id = ? ORDER BY name
`

func (q *Queries) ListShelvesForUser(ctx context.Context, userID int64) ([]Shelf, error) {
	rows, err := q.db.QueryContext(ctx, listShelvesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Shelf{}
	for rows.Next() {
		var i Shelf
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.IconColor,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeBookFromShelf = `-- name: RemoveBookFromShelf :exec
DELETE FROM shelf_book WHERE shelf_id = ? AND book_id = ?
`

type RemoveBookFromShelfParams struct {
	ShelfID int64 `json:"shelf_id"`
	BookID  int64 `json:"book_id"`
}

func (q *Queries) RemoveBookFromShelf(ctx context.Context, arg RemoveBookFromShelfParams) error {
	_, err := q.db.ExecContext(ctx, removeBookFromShelf, arg.ShelfID, arg.BookID)
	return err
}

const updateShelf = `-- name: UpdateShelf :exec
UPDATE shelf SET name = ?, description = ?, icon = ?, icon_color = ?, is_public = ?,
    updated_at = datetime('now')
WHERE id = ? AND user_id = ?
`

type UpdateShelfParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Icon        sql.NullString `json:"icon"`
	IconColor   sql.NullString `json:"icon_color"`
	IsPublic    int64          `json:"is_public"`
	ID          int64          `json:"id"`
	UserID      int64          `json:"user_id"`
}

func (q *Queries) UpdateShelf(ctx context.Context, arg UpdateShelfParams) error {
	_, err := q.db.ExecContext(ctx, updateShelf,
		arg.Name,
		arg.Description,
		arg.Icon,
		arg.IconColor,
		arg.IsPublic,
		arg.ID,
		arg.UserID,
	)
	return err
}
