// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package notebook

import (
	"context"
	"database/sql"
)

const countAnnotationsForUser = `-- name: CountAnnotationsForUser :one
SELECT COUNT(*) FROM annotation WHERE user_id = ?
`

func (q *Queries) CountAnnotationsForUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAnnotationsForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAnnotation = `-- name: CreateAnnotation :one
INSERT INTO annotation (user_id, book_id, book_file_id, type, cfi, page_number, text, note, color)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, book_id, book_file_id, type, cfi, page_number, text, note, color, created_at, updated_at
`

type CreateAnnotationParams struct {
	UserID     int64          `json:"user_id"`
	BookID     int64          `json:"book_id"`
	BookFileID sql.NullInt64  `json:"book_file_id"`
	Type       string         `json:"type"`
	Cfi        sql.NullString `json:"cfi"`
	PageNumber sql.NullInt64  `json:"page_number"`
	Text       sql.NullString `json:"text"`
	Note       sql.NullString `json:"note"`
	Color      string         `json:"color"`
}

func (q *Queries) CreateAnnotation(ctx context.Context, arg CreateAnnotationParams) (Annotation, error) {
	row := q.db.QueryRowContext(ctx, createAnnotation,
		arg.UserID,
		arg.BookID,
		arg.BookFileID,
		arg.Type,
		arg.Cfi,
		arg.PageNumber,
		arg.Text,
		arg.Note,
		arg.Color,
	)
	var i Annotation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BookID,
		&i.BookFileID,
		&i.Type,
		&i.Cfi,
		&i.PageNumber,
		&i.Text,
		&i.Note,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAnnotation = `-- name: DeleteAnnotation :exec
DELETE FROM annotation WHERE id = ? AND user_id = ?
`

type DeleteAnnotationParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteAnnotation(ctx context.Context, arg DeleteAnnotationParams) error {
	_, err := q.db.ExecContext(ctx, deleteAnnotation, arg.ID, arg.UserID)
	return err
}

const getAnnotationByID = `-- name: GetAnnotationByID :one
SELECT id, user_id, book_id, book_file_id, type, cfi, page_number, text, note, color, created_at, updated_at FROM annotation WHERE id = ? LIMIT 1
`

func (q *Queries) GetAnnotationByID(ctx context.Context, id int64) (Annotation, error) {
	row := q.db.QueryRowContext(ctx, getAnnotationByID, id)
	var i Annotation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BookID,
		&i.BookFileID,
		&i.Type,
		&i.Cfi,
		&i.PageNumber,
		&i.Text,
		&i.Note,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllAnnotationsForUser = `-- name: ListAllAnnotationsForUser :many
SELECT a.id, a.user_id, a.book_id, a.book_file_id, a.type, a.cfi, a.page_number, a.text, a.note, a.color, a.created_at, a.updated_at, bm.title as book_title, bm.cover_path
FROM annotation a
JOIN book_metadata bm ON bm.book_id = a.book_id
WHERE a.user_id = ?
ORDER BY a.created_at DESC
LIMIT ? OFFSET ?
`

type ListAllAnnotationsForUserParams struct {
	UserID int64 `json:"user_id"`
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListAllAnnotationsForUserRow struct {
	ID         int64          `json:"id"`
	UserID     int64          `json:"user_id"`
	BookID     int64          `json:"book_id"`
	BookFileID sql.NullInt64  `json:"book_file_id"`
	Type       string         `json:"type"`
	Cfi        sql.NullString `json:"cfi"`
	PageNumber sql.NullInt64  `json:"page_number"`
	Text       sql.NullString `json:"text"`
	Note       sql.NullString `json:"note"`
	Color      string         `json:"color"`
	CreatedAt  string         `json:"created_at"`
	UpdatedAt  string         `json:"updated_at"`
	BookTitle  sql.NullString `json:"book_title"`
	CoverPath  sql.NullString `json:"cover_path"`
}

func (q *Queries) ListAllAnnotationsForUser(ctx context.Context, arg ListAllAnnotationsForUserParams) ([]ListAllAnnotationsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllAnnotationsForUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllAnnotationsForUserRow{}
	for rows.Next() {
		var i ListAllAnnotationsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BookID,
			&i.BookFileID,
			&i.Type,
			&i.Cfi,
			&i.PageNumber,
			&i.Text,
			&i.Note,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BookTitle,
			&i.CoverPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnnotationsForBook = `-- name: ListAnnotationsForBook :many
SELECT id, user_id, book_id, book_file_id, type, cfi, page_number, text, note, color, created_at, updated_at FROM annotation WHERE user_id = ? AND book_id = ?
ORDER BY created_at DESC
`

type ListAnnotationsForBookParams struct {
	UserID int64 `json:"user_id"`
	BookID int64 `json:"book_id"`
}

func (q *Queries) ListAnnotationsForBook(ctx context.Context, arg ListAnnotationsForBookParams) ([]Annotation, error) {
	rows, err := q.db.QueryContext(ctx, listAnnotationsForBook, arg.UserID, arg.BookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Annotation{}
	for rows.Next() {
		var i Annotation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BookID,
			&i.BookFileID,
			&i.Type,
			&i.Cfi,
			&i.PageNumber,
			&i.Text,
			&i.Note,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnnotationsForFile = `-- name: ListAnnotationsForFile :many
SELECT id, user_id, book_id, book_file_id, type, cfi, page_number, text, note, color, created_at, updated_at FROM annotation WHERE user_id = ? AND book_file_id = ?
ORDER BY created_at DESC
`

type ListAnnotationsForFileParams struct {
	UserID     int64         `json:"user_id"`
	BookFileID sql.NullInt64 `json:"book_file_id"`
}

func (q *Queries) ListAnnotationsForFile(ctx context.Context, arg ListAnnotationsForFileParams) ([]Annotation, error) {
	rows, err := q.db.QueryContext(ctx, listAnnotationsForFile, arg.UserID, arg.BookFileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Annotation{}
	for rows.Next() {
		var i Annotation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BookID,
			&i.BookFileID,
			&i.Type,
			&i.Cfi,
			&i.PageNumber,
			&i.Text,
			&i.Note,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAnnotation = `-- name: UpdateAnnotation :exec
UPDATE annotation SET note = ?, color = ?, updated_at = datetime('now')
WHERE id = ? AND user_id = ?
`

type UpdateAnnotationParams struct {
	Note   sql.NullString `json:"note"`
	Color  string         `json:"color"`
	ID     int64          `json:"id"`
	UserID int64          `json:"user_id"`
}

func (q *Queries) UpdateAnnotation(ctx context.Context, arg UpdateAnnotationParams) error {
	_, err := q.db.ExecContext(ctx, updateAnnotation,
		arg.Note,
		arg.Color,
		arg.ID,
		arg.UserID,
	)
	return err
}
